### ISSUE TITLE
Notification en boucle

### ISSUE THREAD

**Issue by nono723** [aassif/pvr.freebox#1]
Bonjour,

Après avoir installé le plugin, j'ai une notification "PVR Freebox TV: Autorisation requise" qui apparaît et disparait.

J'ai testé sur ma tablette ARMv7 et sur la Mini4k (ARMv7) (j'ai pas de rPi ou de ARMv8)

**Comment by ninjaw** [comment]
ce qui est le fonctionnement normal...

**Comment by nono723** [comment]
?

**Comment by aassif** [comment]
La gestion des enregistrements nécessite une validation physique sur le Freebox Server.
