### ISSUE TITLE
version de libssl sur raspbian

### ISSUE THREAD

**Issue by CircleCode** [aassif/pvr.freebox#10]
J'utilise kodi installé sur raspbian sur un raspberry pi 3

Suite à l'installation, l'addon refusait de se charger.
L'erreur était : `libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

En effet, raspbian a mis à jour libssl vers la version 1.0.2.

Pour info, des liens symboliques semblent résoudre le problèeme :
```
ln -s libssl.so.1.0.2 libssl.so.1.0.0
ln -s libcrypto.so.1.0.2 libcrypto.so.1.0.0
```
En revanche, je me demande si ça peut poser des problèmes par ailleurs

**Comment by aassif** [comment]
Désolé pour cet inconvénient.
Je ne pense pas que les liens symboliques soient problématiques.

Comme je l'ai déjà dit ailleurs, difficile pour moi de compiler pour toutes les variantes.
J'ai demandé à intégrer le repo officiel mais, si la situation se débloque, cela ne se fera pas avant la prochaine version de Kodi.

**Comment by CircleCode** [comment]
> Désolé pour cet inconvénient.

Ce n'est pas bien grave, juste un retour. Peut-être une note dans le readme, ou une page de wiki de *troubleshooting* pourrait compiler ces informations s'il est impossible de fonctionner avec plusieurs versions de `ssl`.

----
Note : de mon côté, si rien n'est envisagé (ou si c'est trop complexe de supporter plusieurs versions), on peut clore.

**Comment by aassif** [comment]
La bibliothèque sera désormais compilée en statique :)
