### ISSUE TITLE
Please branch from "Nexus" to "Omega"

### ISSUE THREAD

**Issue by phunkyfish** [aassif/pvr.freebox#100]
The build pipelines are setup, once you are done let me know and we can re-enable this add-on for Omega (Kodi 21) builds

**Comment by aassif** [comment]
I think it's ready.

**Comment by phunkyfish** [comment]
PR created: https://github.com/xbmc/repo-binary-addons/pull/157

**Comment by phunkyfish** [comment]
PR merged, thanks!
