### ISSUE TITLE
Permettre de forcer le port rtsp

### ISSUE THREAD

**Issue by CircleCode** [aassif/pvr.freebox#14]
Dans certaines conditions (notamment en mode bridge, lorsque le routage est fait par un routeur qui n'a pas de mécanisme de suivi des sessions RTSP (`conntracker`)), il est nécessaire de mettre en place une redirection de port explicite, ce qui nécessite de connaître le port utilisé pour la session rtsp.
Note : voir https://www.bortzmeyer.org/turris-bis.html pour des détails sur la redirection en question.

**Comment by aassif** [comment]
J'ai déjà cherché et, bien que FFmpeg en soit capable, Kodi ne permet pas de spécifier les ports RTSP.

**Comment by CircleCode** [comment]
questions de brainstorming (je ne maitrise pas du tout ces aspects)
Je suppose que Kodi utilise ffmpeg ? Dans ce cas, n'est-il pas possible de forcer ce port de manière globale au système directement pour ffmpeg ?

**Comment by CircleCode** [comment]
ou encore, comment ffmpeg est-il appelé par kodi ? peut-être est-il possible d'écrire un wrapper qui passe les bonnes options dans ce cas particulier ?

**Comment by CircleCode** [comment]
bon, en ce qui me concerne, problème résolu par l'activation d'un conntrack rtsp.
Pour mémo à ceux qui rencontreraient le problème sous openwrt :
- installation de kmod-ipt-nathelper-rtsp
- activation du helper (`echo 1 > /proc/sys/net/netfilter/nf_conntrack_helper` pour du temporaire, ou `echo "net.netfilter.nf_conntrack_helper=1" > /etc/sysctl.conf` pour du permanent)

**Comment by erwann2000** [comment]
> bon, en ce qui me concerne, problème résolu par l'activation d'un conntrack rtsp.
> Pour mémo à ceux qui rencontreraient le problème sous openwrt :
> 
> * installation de kmod-ipt-nathelper-rtsp
> * activation du helper (`echo 1 > /proc/sys/net/netfilter/nf_conntrack_helper` pour du temporaire, ou `echo "net.netfilter.nf_conntrack_helper=1" > /etc/sysctl.conf` pour du permanent)

un double signe supérieur est préférable afin de ne pas écraser le contenu du fichier /etc/sysctl.conf
echo "net.netfilter.nf_conntrack_helper=1" >> /etc/sysctl.conf

En tout cas merci pour le tuyau de l'activation du helper

**Comment by 66enligne** [comment]
Cela ne fonctionne plus avec la version 22.03 de openwrt passé de fw3 à fw4
avez vous trouvé une solution?

**Comment by 66enligne** [comment]
Désolé pour le message précédent. Tout est OK c'est moi qui ai fait une erreur
