### ISSUE TITLE
windows: openssl dependency not working/missing

### ISSUE THREAD

**Issue by ksooo** [aassif/pvr.freebox#15]
Jenkins Windows build currently fails.

vfs.sftp does it right. => https://github.com/xbmc/vfs.sftp/tree/Leia/depends/windows/openssl

**Comment by aassif** [comment]
Should be fine now :)

**Comment by aassif** [comment]
Not yet. Issues with RapidJSON.

**Comment by ksooo** [comment]
=> d:\jenkins\workspace\binary-addons\kodi-windows-x86_64-matrix\tools\depends\target\binary-addons\pvr.freebox\src\Freebox.h(373): error C2059: syntax error: 'constant'
d:\jenkins\workspace\binary-addons\kodi-windows-x86_64-matrix\tools\depends\target\binary-addons\pvr.freebox\src\Freebox.h(373): error C2238: unexpected token(s) preceding ';'

**Comment by ksooo** [comment]
Maybe there is some nonsense define for "DELETE" on Windows? Just guessing.

**Comment by aassif** [comment]
Highly likely!

**Comment by aassif** [comment]
https://stackoverflow.com/a/1271185

**Comment by ksooo** [comment]
wtf. Windows.

**Comment by ksooo** [comment]
I suggest to rename the conflicting method.

**Comment by aassif** [comment]
Instead of this plain old #undef?
https://github.com/aassif/pvr.freebox/commit/3abf48d006d3e83630d2170902adb0cc81b5d367

**Comment by ksooo** [comment]
I would opt for a "safe" method name, yes.

**Comment by ksooo** [comment]
But ofc your decision.

**Comment by ksooo** [comment]
sigh...

next one :

D:\jenkins\workspace\binary-addons\kodi-windows-x86_64-Matrix\tools\depends\target\binary-addons\pvr.freebox\src\Freebox.cpp(278): error C2065: '_POSIX_HOST_NAME_MAX': undeclared identifier
D:\jenkins\workspace\binary-addons\kodi-windows-x86_64-Matrix\tools\depends\target\binary-addons\pvr.freebox\src\Freebox.cpp(278): error C2133: 'hostname': unknown size
D:\jenkins\workspace\binary-addons\kodi-windows-x86_64-Matrix\tools\depends\target\binary-addons\pvr.freebox\src\Freebox.cpp(279): error C2065: '_POSIX_HOST_NAME_MAX': undeclared identifier

**Comment by aassif** [comment]
This one was predictable. I need to use `GetComputerName` instead of `gethostname`.
Or, how about I disable the whole Windows part until I get ahold of a Windows machine?

**Comment by aassif** [comment]
But I can manage this through Jenkins, too.
I'm watching the builds go as we speak.

**Comment by ksooo** [comment]
> Or, how about I disable the whole Windows part until I get ahold of a Windows machine?

 Nope. Let's get this build done now.

**Comment by ksooo** [comment]
> I'm watching the builds go as we speak.

 But you cannot trigger the build. It's me doing this.

**Comment by ksooo** [comment]
> I need to use GetComputerName instead of gethostname.

I don't think so =>  https://docs.microsoft.com/en-us/windows/desktop/api/winsock/nf-winsock-gethostname

**Comment by ksooo** [comment]
```
#ifndef _POSIX_HOST_NAME_MAX
#define _POSIX_HOST_NAME_MAX 64
#endif
```

?

**Comment by aassif** [comment]
The doc says 256 bytes, so I did something similar: https://github.com/aassif/pvr.freebox/commit/7c53002506e027a5f28e1cdaec40df4836b67c40

**Comment by ksooo** [comment]
Not sure the platform defs are okay. In other addons we use TARGET_WINDOWS for instance.

Why do you not simply use ifndef instead of "assuming" what is defined I for which platform?

**Comment by aassif** [comment]
Done!

**Comment by ksooo** [comment]
We made it. :-)

Your addon will appear in official Kodi Matrix addon repositoy (for the relevant platforms - Android, macOS, Windows) in the next hour. => http://mirrors.kodi.tv/addons/matrix/

Linux is handled diferently (as you should already know).

**Comment by ksooo** [comment]
Whenever you want to release and publish a new version, from now on, first bump addon version and changelog, then create a tag for the respective code revision (name does not really matter - I suggest major.minor.micro-kodiversion -> 2.0.1-Matrix). Kodi jenkins will pick up the latest tag per branch automatically, then will build it and publish to addon repository.

**Comment by aassif** [comment]
> We made it. :-)

Yeah! Thank you so much!

> Kodi jenkins will pick up the latest tag per branch automatically, then will build it and publish to addon repository.

No more Android cross-compiling :)
