### ISSUE TITLE
RPi2 build failed 

### ISSUE THREAD

**Issue by mkreisl** [aassif/pvr.freebox#16]
Was trying to build addon today. Unfortunately build fails with error:
```
In file included from /home/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/pvr.freebox/src/client.cpp:24:0:
/home/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/pvr.freebox/src/Freebox.h: In member function 'int Index<K>::operator()(const K&)':
/home/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/pvr.freebox/src/Freebox.h:79:12: error: expected unqualified-id before '[' token
       auto [i, success] = m_map.emplace (key, m_id);
            ^
/home/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/pvr.freebox/src/Freebox.h:80:14: error: 'success' was not declared in this scope
       return success ? m_id++ : i->second;
              ^~~~~~~
/home/xbian/xbian-package-xbmc/build/rpi2-matrix/working/cmake/addons/build/pvr.freebox/src/Freebox.h:80:33: error: 'i' was not declared in this scope
       return success ? m_id++ : i->second;
                                 ^
CMakeFiles/pvr.freebox.dir/build.make:62: recipe for target 'CMakeFiles/pvr.freebox.dir/src/client.cpp.o' failed
```

Using cross-compiling with gcc 6.3.0 / Debian Stretch

**Comment by aassif** [comment]
Does your toolchain support C++17?

**Comment by mkreisl** [comment]
> Does your toolchain support C++17?

Partly, see https://gcc.gnu.org/projects/cxx-status.html#cxx17

I don't think that this is good idea to write an addon which requires fully supported C++17. If you look to all other binary addons, the highest required C++ is 14. And GCC marked C++17 still as experimental:

```
Important: Because the final ISO C++17 standard is still new, GCC's support is experimental. No attempt will be made to maintain backward compatibility with implementations of C++17 features that do not reflect the final standard
```

**Comment by aassif** [comment]
Well, structured bindings are part of the C++17 final standard and I believe new addons should follow new standards.
Anyway, it's an easy fix and I'll gladly provide support for C++14 :)

**Comment by ksooo** [comment]
Kodi build env is still c++11. Just saying.

**Comment by aassif** [comment]
@mkreisl Should be fixed. Could you please confirm?

**Comment by mkreisl** [comment]
> Kodi build env is still c++11. Just saying.

Yes, I know that. Was just doing a quick grep for `CMAKE_CXX_STANDARD` in my binary addon tree and found a lot of `set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT "14")` and was not deeper investigating what that setting does

**Comment by mkreisl** [comment]
> Should be fixed. Could you please confirm?

Yes, it is fixed now. Many thanks for your fast response. I really appreciate that

:+1:
