### ISSUE TITLE
Ne s'installe pas sur LibreElec RPI4

### ISSUE THREAD

**Issue by CalimeroOeuf** [aassif/pvr.freebox#18]
Erreur d'installation sur LibreElec RPI4

Y'aura-t-il une mise a jour de ce plug-in qui a l'air excellent ?

**Comment by ninjaw** [comment]
+1 pas de mise a jour depuis bug d'installation general ?

**Comment by aassif** [comment]
J'ai constaté ce problème avant de partir en vacances.
J'essaierai de regarder ça à mon retour.

**Comment by aassif** [comment]
Version LibreELEC 9.1 pour RPi 4 ajoutée à la _release_ 2.0.0 !

**Comment by CalimeroOeuf** [comment]
Parfait, nickel sur mon RPI4 ! Merci !
