### ISSUE TITLE
Plus de version compilée

### ISSUE THREAD

**Issue by chfarges** [aassif/pvr.freebox#19]
Bonjour,

Dans la partie release, on ne trouve plus de version compilée pour les dernières versions. La procédure pour installer a-t’elle changé ?

Bonne journée !

**Comment by CalimeroOeuf** [comment]
Dommage, je suis incapable de compiler cet add-on.
J'aimerai tant qu'une mise a jour soit faites pour le Raspberry PI4 avec Libreelec

**Comment by aassif** [comment]
Les dernières releases sont automatiquement compilées par le Jenkins de Kodi *mais* elles sont dédiées à Matrix.
La version 2.0.0 est la dernière version compatible Leia.

**Comment by aassif** [comment]
> J'aimerai tant qu'une mise a jour soit faites pour le Raspberry PI4 avec Libreelec

https://github.com/aassif/pvr.freebox/issues/18

**Comment by chfarges** [comment]
Merci pour la réponse ! C’est dommage, d’autant que la prochaine version de Jodi sur libreelec n’est pas prête d’arriver je pense. Bonne journée et merci pour ce super plugin !

**Comment by ninjaw** [comment]
Statistiquement il va falloir attendre entre 6 et 18 mois. Et la ca sera une grande premiere : la gestion native de la freebox dans kodi pour tous ! J'ai du mal a comprendre ce qu'il en est pour retropie qui lui aussi n'arrivait pas a installer alors qu'a priori c'est le meme os ? a l'epoque tu avais dis qu'il y avait une incompatibilité meme sur RPI3
