### ISSUE TITLE
Notification en boucle.

### ISSUE THREAD

**Issue by Jason-X60** [aassif/pvr.freebox#2]
J'ai la notification sur Kodi 18, Android TV qui apparaît en boucle mais rien n'apparaît sur ma Freebox pour valider celle-ci. Je connait pourtant la manipulation mais cette fois-ci je sèche... En tous cas ce PVR est très prometteur.

**Comment by ninjaw** [comment]
Reinstallez le plugin

**Comment by Jason-X60** [comment]
Parfait cela à fonctionné
