### ISSUE TITLE
Ne fonctionne pas sur librelec 9.2

### ISSUE THREAD

**Issue by Miaourt** [aassif/pvr.freebox#23]
Salut, merci pour ton super plugin !
J'ai essayé d'installer le plugin pour mon RPI4 sous librelec 9.2, et malheureusement aucuns flux vidéos ne semblent fonctionner, ni les vignettes des chaînes.

Cependant, on obtient bien le programme et une liste des enregistrements (qui malheureusement ne marchent pas non plus.

J'ai pas plus d'info à te fournir comme ça, si tu saurais où me diriger pour te filer des logs qui t'aiderais, je suis tout ouï :)

**Comment by ninjaw** [comment]
Pour ma part ca fonctionne parfaitement sur librelec 9.2 RPI4.
ps: tu es tout ouïe

**Comment by Miaourt** [comment]
@ninjaw salut ! T'as téléchargé le zip RPI4 de la 2.0.0 ? Puis juste chargé ça via l'installateur de kodi ?

**Comment by ninjaw** [comment]
Oui, mais je l'ai installé avec la verson finale

**Comment by Miaourt** [comment]
@ninjaw comment avez-vous fait ? Kodi sur la 9.2 de libreelec n'est pas la version Matrix, c'est donc impossible pour moi

**Comment by aassif** [comment]
Quelle type de Freebox avez-vous ?
Utilisez-vous un routeur ?

**Comment by Miaourt** [comment]
@aassif après avoir réinstaller une seconde fois tout fonctionne, désolé du report ^^'
