### ISSUE TITLE
Paquet Debian ?

### ISSUE THREAD

**Issue by malaterre** [aassif/pvr.freebox#24]
Est-ce que ca a du sens de pousser le plugin dans Debian ? Je vois par ex:

* https://tracker.debian.org/pkg/kodi-pvr-iptvsimple

Merci de me confirmer que c'est ok (malat@d.o).

**Comment by aassif** [comment]
La version Leia n'est pas reconnue par Kodi et ne le sera probablement jamais.

La version Matrix sera, elle, intégrée dès la sortie officielle de Kodi 19.
Elle est déjà disponible sur les repos [Android, OS X et Windows](https://mirrors.kodi.tv/addons/matrix/).
Pour le Raspberry Pi, elle fait partie des betas [LibreELEC](https://forum.kodi.tv/showthread.php?tid=343068&pid=2906246#pid2906246) et [OSMC](https://discourse.osmc.tv/t/kodi-19-matrix-nightly-builds-for-raspberry-pi/79407/199).
Enfin, pour en revenir à Linux, elle est intégrée au [PPA officiel de Kodi](https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly/+packages?field.name_filter=kodi-pvr-freebox&field.status_filter=published&field.series_filter=).

En l'occurrence, le package "kodi-pvr-iptvsimple" auquel vous faites référence est basé sur la version 2.4.4 alors que les versions actuelles sont la 3.8.8 pour Leia et la 4.8.4 pour Matrix.
Il en va de même pour "kodi-pvr-hts", par exemple (3.4.13-1 vs. 4.4.20/5.3.0).

Bref, j'ai l'impression que seul le PPA est maintenu.
J'ignore pourquoi mais cela semble être l'unique canal officiel.

Merci pour votre intérêt !

**Comment by prahal** [comment]
Ce serait une très bonne idée d'avoir un paquet dans Debian.
Le PPA ne supporte officiellement que Ubuntu.

Pour Debian, être maintenu n'a pas de lien avec fournir la dernière version au moment de sa sortie. Cela implique que le mainteneur Debian fait les mises à jour de sécurité.
Mais Debian unstable, la version pour régler les problèmes d'intégration, a des versions à jour.

J'utilise Kodi sous Debian et avoir un paquet intégré à Debian me permettrait de garder le support des bugs par les mainteneurs Debian pour Kodi.
Including ppa can replace Debian packages and introduce new bugs or ones already patched in the Debian packages.

Depuis au moins un an, le support de Kodi dans Debian est très actif.
