### ISSUE TITLE
Problem with 2.0 version and LibreELEC X86_64

### ISSUE THREAD

**Issue by chfarges** [aassif/pvr.freebox#25]
Hello !
I have installed LibreELEC 9.2 with Kodi 18.5 on X86_64 and I have an error when launching the addon. I saw that a newer version was compiled for RPI. May be it is the same issue. Could you please compile a newer version for LibreELEC X86_64 ? Thanks !!

**Comment by aassif** [comment]
https://github.com/aassif/pvr.freebox/releases/download/2.0.1-Leia/pvr.freebox-libreelec9.2-x86_64.zip

**Comment by chfarges** [comment]
Thank you very much ! I will try this tomorrow !

**Comment by chfarges** [comment]
Hi ! Just to tell you that it works great ! Thanks !!!
