### ISSUE TITLE
Erreur " autorisez Kodi sur freebox server" <RESOLU>

### ISSUE THREAD

**Issue by yack33800** [aassif/pvr.freebox#26]
Bonjour,
Sur Freebox révolution V6 et pvr.freebox-2.0, j'ai un message d'erreur qui s'affiche régulièrement même en dehors de pvr.freebox demandant d'autoriser Kodi sur le serveur de la freebox.
La reinstallation de l'addon ne change rien.

j'ai déjà configuré celle-ci en activant UPnP AV dans les paramètres de l'OS freebox et redémarré les équipements.

Au lancement de PVR.freebox j'ai une indication disant que 902 chaines sont trouvées et les epg fonctionnent mais pas les vidéos.

Si je lance dans le module video de Kodi, la liste des chaines http://mafreebox.freebox.fr/freeboxtv/playlist.m3u cela marche bien montrant ainsi que la fonction multiposte est opérationnelle.

Merci de remédier à cette anomalie et/ou voire d'autoriser dans le paramétrage, la liste m3u précédente. 

Cdlt

version installée 2.0.1-Leia avec pvr.freebox-2.0-android-armv7.zip

**Comment by aassif** [comment]
Bonsoir,

Si les vidéos ne fonctionnent pas, il s'agit probablement d'un problème réseau.
Le fait d'avoir accès à la playlist ne garantit pas de pouvoir lire les les flux.
Utilisez-vous un routeur ?

En ce qui concerne le problème du message "Autorisez Kodi sur Freebox Server", vous n'avez probablement jamais validé physiquement l'autorisation sur le Server (an appuyant sur la flèche de droite).
De ce fait, le _plugin_ s'est retrouvé en situation de _timeout_.
Une solution consiste à supprimer le fichier `app_token.txt` dans le répertoire `userdata/addon_data/pvr.freebox/`.

**Comment by yack33800** [comment]
Bonsoir,
je n'ai pas de routeur
je lis les video de la playlist tant sur kodi, qu'avec vlc sur le systeme android

Pour le message "Autorisez kodi..." sur l'afficheur du server il n'y a pas de message, et dans les menus sur le LCD rien pour valider cette fonction

Désolé mais je vois pas userdata avec es explorer sur le X96H. j'ai regardeé aussi  dans les repertoires android et kodi mais je n'ai rien trouvé.
Veuillez me guider
cordialement

**Comment by ninjaw** [comment]
Si je me trompes pas c est l erreur hyper classique de reinstall add-on. A
noter qu ES a été banni du playstore il y a un an

**Comment by yack33800** [comment]
j'ai finalement trouvé et supprimé le fichier app_token.txt
Désormais les vidéos s'affichent mais j'ai toujours la mini fenêtre de temps en temps demandant d'autoriser Kodi sur le serveur de la freebox !

Quel est l'explorateur autre qu'ES que vous recommandé ?

merci pour dejà avoir reglé partiellement le pb

**Comment by ninjaw** [comment]
Pour ma part j'ai décidé de passer sur solid explorer

**Comment by aassif** [comment]
Essayez de procéder dans cet ordre :
1 - Désinstaller le plugin ;
2 - Supprimer le fichier "app_token.txt" ;
3 - Ré-installer le plugin.

Dans cet ordre, le message "Autoriser Kodi sur XXX ?" devrait apparaître à nouveau sur le Freebox Server.

**Comment by aassif** [comment]
Essayez de procéder dans cet ordre :
1 - Désinstaller le plugin ;
2 - Supprimer le fichier `app_token.txt` ;
3 - Ré-installer le plugin.

Normalement, le message "Autoriser Kodi sur XXX ?" devrait apparaître sur le Freebox Server.
Appuyez alors sur la flèche de droite.

**Comment by yack33800** [comment]
Bonjour,
Enfin cela marche !
La désinstallation du plugin ne laisse pas de trace de app_token.txt
Lors de la reinstallation du plugin, il apparait sur la freebox server fugitivement "autoriser Kodi ur xxxx" l'appui sur le bouton droite valide l'autorisation.
les messages fugitifs Erreur " autorisez Kodi sur freebox server" ont disparu
PB resolu
merci
