### ISSUE TITLE
pvr.freebox impossible à démarrer

### ISSUE THREAD

**Issue by malaterre** [aassif/pvr.freebox#28]
J'ai installé le plugin pré-compilé: `pvr.freebox-libreelec9.2-rpi2.zip` sur mon LibreElec 9.2.0 (mis à jour ajd).

J'ai eu:

1. Message des 900 chaines disponibles,
2. Authorisation du freebox server apparait

Je séléctionne flêche droite (=oui) sur ma Freebox Mini 4K. Le message d'authorisation n'apparait plus à l'écran.

Problème: La fonction 'Exectuer':

* https://ninjaw.files.wordpress.com/2018/12/20181212_211443.jpg?w=604

Est grisée chez moi, impossible de démarrer le plugin.

Je ne vois rien dans les log (`/storage/.kodi/kodi.log`). J'ai vu passé dans d'autre message qu'il faut redémarrer (ce que j'ai fait). J'ai aussi cliquer 'désinstaller' puis reinstaller depuis le fichier zip `pvr.freebox-libreelec9.2-rpi2.zip`...toujours sans succès.

Reference:

1. Version du micrologiciel: 4.0.7
2. Version du matériel: Freebox Server Mini (r2)

**Comment by aassif** [comment]
Bonjour,

Il est tout à fait normal que la case 'Exécuter' soit grisée.

Si le plugin annonce 900 chaînes disponibles, elles devraient se trouver dans la catégorie TV.
N'est-ce pas le cas ?

À bientôt !

**Comment by malaterre** [comment]
@aassif Encore un cas de PEBCAK cette fois entre le canapé et la télé. Désolé.

**Comment by ksooo** [comment]
If you french guys only would be willing to communicate in English you could get help from all over the world. With you sticking to your local language I'm out of all of this, although I would be willing to and maybe even capable to help...

**Comment by aassif** [comment]
Sorry, Kai.

I can try to translate every issue from French to English.
Can I answer in both languages?

Anyway, that's probably my bad as I chose French for the `README` on the home page.

**Comment by ksooo** [comment]
Best would be to communicate only in English in the first place. Google Translate and friends are good enough nowadays to produce something that is at least understandable.
