### ISSUE TITLE
Texte manquant dans les settings

### ISSUE THREAD

**Issue by MaximeCheramy** [aassif/pvr.freebox#3]
Version 2.0b1 sur rp3, kodi 18

Dans les settings je n'ai pas de texte. Les options semblent correspondre à ce que j'ai pu lire dans le code source mais sans le texte ce n'est pas vraiment utilisable :).

**Comment by MaximeCheramy** [comment]
Mon interface est en anglais, c'est peut-être pour ça. J'ai tenté d'installer une version modifiée avec un fichier de traduction en_gb et depuis dans les settings ça s'affiche correctement. J'ai ensuite tenté de réinstaller la version d'origine sans la traduction mais les settings s'affichent toujours... Donc je ne peux pas garantir que ce soit la correction ou si c'est juste la n-ième réinstallation qui a fait que depuis ça marche...

**Comment by aassif** [comment]
Désolé, j'étais en vacances ;)

Effectivement, je pense que c'était dû à l'absence de fichiers ressources en anglais.

Je n'ai pas géré d'autres langues que le français puisque les possesseurs de Freebox sont généralement francophones. Il faudra néanmoins y remédier.
