### ISSUE TITLE
Support des radios

### ISSUE THREAD

**Issue by Glandos** [aassif/pvr.freebox#32]
Je sais que ce n'est pas très demandé, ni peut-être encore moins utilisé, mais est-il possible d'avoir le support des radios ?

Et si c'est non, au moins, on aura la réponse :)

**Comment by ninjaw** [comment]
en fait on a deja la reponse, meme si la radsio est disponible, la revolution refuse d'en fournir la liste, donc non

**Comment by Glandos** [comment]
OK, c'est juste pour l'inscrire dans le projet.
Si un jour le Freebox Serveur ressert cette liste, ça sera la fête :tada:
