### ISSUE TITLE
Please stop using the same rev for Matrix and Leia releases

### ISSUE THREAD

**Issue by MilhouseVH** [aassif/pvr.freebox#33]
Thank you.

**Comment by aassif** [comment]
I'm sorry. What do you mean?
They should differ. Don't they?

**Comment by MilhouseVH** [comment]
Further to this, when the 2.0.1-Leia release is downloaded, the source code is actually the 2.2.0-Matrix release. So you may need to re-tag the latest releases correctly.

> I'm sorry. What do you mean?
They should differ. Don't they?

See here:

![s1](https://i.imgur.com/5MpSwNY.png)

You've used the same rev 7fb6d449214cf9366049a667ec9bd6d5c3216594 for both 2.2.0-Matrix and 2.0.1-Leia.

**Comment by MilhouseVH** [comment]
I'm guessing your 2.0.1-Leia tag should be using rev 40c05be07720fbbd1cba8404e5edfa26298cb3de or possibly rev 267eff873a7c366c6f929deafac506136a4171c9, but definitely NOT 7fb6d449214cf9366049a667ec9bd6d5c3216594 as that is 2.2.0-Matrix. :smile:

**Comment by aassif** [comment]
I'll try to fix this mess.

**Comment by MilhouseVH** [comment]
Thanks!

**Comment by aassif** [comment]
Is that OK now?

**Comment by MilhouseVH** [comment]
Yes that looks good now, thanks!
