### ISSUE TITLE
Installation, Compilation

### ISSUE THREAD

**Issue by kikiminou** [aassif/pvr.freebox#35]
Vous n'expliquez pas comment installer votre addon pvr.freebox sous Linux et il ne me semble pas qu'il soit proposé de binaire pour Linux Raspbian avec Kodi Lea. Pouvez-vous, s'il vous plaît, donner la procédure de compilation en précisant bien les prérequis s'il y en a? Merci d'avance.

**Comment by aassif** [comment]
Voici la procédure, identique à celle de tout PVR.

Il faut tout d'abord cloner les deux projets :
`git clone -b 18.6-Leia https://github.com/xbmc/xbmc.git kodi`
`git clone -b Leia https://github.com/aassif/pvr.freebox.git`

En l'état, il faut ajouter la ligne suivante à la fin de `CMakeLists.txt` :
`set_property(TARGET pvr.freebox PROPERTY CXX_STANDARD 17)`

Puis configurer le projet :
`ROOT=$PWD`
`cd pvr.freebox`
`mkdir build`
`cmake
  -DADDONS_TO_BUILD=pvr.freebox
  -DADDON_SRC_PREFIX=$ROOT
  -DCMAKE_BUILD_TYPE=Release
  -DCMAKE_INSTALL_PREFIX=$ROOT/kodi/addons
  -DPACKAGE_ZIP=1
  $ROOT/kodi/cmake/addons`

Et enfin le compiler :
`make package-addons`

L'archive générée se situera dans le répertoire `pvr.freebox-prefix/src/pvr.freebox-build`.

En réalité, je vous conseille plutôt de passer aux _nightlies_ de Matrix :)

**Comment by denics** [comment]
Salut, désolé de resortir ca, mais je tombe sur: 

`CMake Error at CMakeLists.txt:441 (message):
  pvr.freebox did not match any of the supported addons.  A list of supported
  addons can be viewed by building the 'supported_addons' target.  Addon
  definitions are loaded from ADDONS_DEFINITION_DIR
  (/home/pi/Git/freebox/kodi/cmake/addons/addons).`

sur mon raspbian RPi3

**Comment by aassif** [comment]
Puisque `pvr.freebox` ne fait pas partie du dépôt Leia officiel, il faut utiliser le mien :
`sed -i 's/xbmc/aassif/' kodi/cmake/addons/bootstrap/repositories/binary-addons.txt`

**Comment by denics** [comment]
Même avec cette modif j'ai:

```
Release -DCMAKE_INSTALL_PREFIX=$ROOT/kodi/addons -DPACKAGE_ZIP=1 $ROOT/kodi/cmake/addons
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /home/pi/Git/freebox/pvr.freebox/build/zips)
-- Building following addons: pvr.freebox
-- Overriding addon source directory prefix: /home/pi/Git/freebox
-- 
-- ---- Preparing general dependencies ----
-- Processing /home/pi/Git/freebox/kodi/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;p8-platform
-- Processing /home/pi/Git/freebox/kodi/cmake/addons/depends/common/p8-platform/p8-platform.txt
-- p8-platform url: https://github.com/xbmc/platform.git
-- Processing /home/pi/Git/freebox/kodi/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /home/pi/Git/freebox/kodi/cmake/addons/depends/linux/CMakeLists.txt found
-- 
CMake Error at CMakeLists.txt:441 (message):
  pvr.freebox did not match any of the supported addons.  A list of supported
  addons can be viewed by building the 'supported_addons' target.  Addon
  definitions are loaded from ADDONS_DEFINITION_DIR
  (/home/pi/Git/freebox/kodi/cmake/addons/addons).


-- Configuring incomplete, errors occurred!
See also "/home/pi/Git/freebox/pvr.freebox/CMakeFiles/CMakeOutput.log".
```

La commande que je lance est :
`~/Git/freebox/pvr.freebox $ cmake -DADDONS_TO_BUILD=pvr.freebox -DADDON_SRC_PREFIX=$ROOT -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$ROOT/kodi/addons -DPACKAGE_ZIP=1 $ROOT/kodi/cmake/addons`

Merci!

**Comment by aassif** [comment]
Peut-être une histoire de `bootstrap` ?
`cd kodi/tools/depends/`
`./bootstrap`

**Comment by aassif** [comment]
Puis relancer `cmake` dans `pvr.freebox`.

**Comment by denics** [comment]
Pas encore :(
Ensuite, si on arrive a le faire marcher, on pourrait faire des CI pour compiler les differents versions (je sais le faire sur gitlab)

**Comment by denics** [comment]
J'ai trouvé ca qui nous aide pas trop: https://github.com/kodi-pvr/pvr.iptvsimple/issues/79

**Comment by aassif** [comment]
Je suis _presque_ sûr que c'est le _bootstrap_.
Essayez à partir d'un nouveau clone du projet kodi.

**Comment by aassif** [comment]
Les CI sont déjà en place pour Matrix.
https://jenkins.kodi.tv/view/Addons/job/aassif/job/pvr.freebox/job/Matrix/
