### ISSUE TITLE
Error when installing on PC

### ISSUE THREAD

**Issue by chfarges** [aassif/pvr.freebox#4]
Hello,
I tried to install on LibreElec on a X86_64 PC with AMD processor and Nvidia graphic cars but it does not install. I get a message saying that the addon could not be loaded. I chose the 2.0.0 beta2 Linux version. Are you aware of this issue ? Should I do something else ? 
Thanks for your help
(Installs well on a Raspberry Pi)

**Comment by aassif** [comment]
Bonjour !
Je pense qu'il faut une version spéciale LibreElec.
Si j'ai le temps, je compile ça ce week-end.
Bonne soirée !

**Comment by chfarges** [comment]
Merci beaucoup pour ta réponse rapide ! En fait ça fonctionne sous LibreElec installé sur mon Raspberry mais pas sous LibreElec installé sur mon PC. Maintenant il manque peut-être certains composants sur la version PC. Si je peux aider avec des Logs ou autres, n’hésite pas.

**Comment by aassif** [comment]
Bonjour !
Pouvez-vous tester la version LibreElec x86_64 ?

**Comment by chfarges** [comment]
Bonjour ! Et d'abord merci et bravo pour la réactivité !

Alors avec la nouvelle version, ça s'installe bien. Après l'installation, j'avais bien accès aux chaines IP mais pas aux chaines TNT.
Du coup sur mon Freebox player, j'ai fait une recherche de chaines TNT avec succès (elles n'étaient pas installées). Je suis revenu sur LibreElec, j'ai désactivé et réactivé l'addon PVT mais toujours pas de TNT. J'ai ensuite vu sur internet que parfois il fallait redémarrer le Freebox server après avoir installé les chaines TNT. J'ai fait ça mais ça n'a rien changé.
Par contre, depuis que j'ai redémarré le Freebox server, j'ai en permanence un message dans Kodi : "PVR Freebox TV Autorisation requise". Le message fait un pop-up toutes les 5 secondes environ. La TV IP marche toujours mais je n'arrive pas à faire disparaître ce message (j'ai essayé de redémarrer, désinstaller et réinstaller l'addon PVR Freebox, rien n'y fait).
Finalement je suis allé voir du côté de mon raspberry. Là surprise j'ai les chaines TNT aussi, par contre le message "PVR Freebox TV Autorisation requise" est présent là aussi alors qu'il n'y était pas avant non plus.
Je me demande si lorsque j'ai fait le redémarrage du Freebox server il n'y a pas eu une mise à jour (je suis en version 4.0.4 maintenant) qui cause ce souci.
Une idée pour m'aider pour le message qui apparaît sans arrêt et les chaines TNT ? Je sens qu'on y est presque ;-)
PS : sur le raspberry ça fonctionne moins bien que sur le PC. Lorsque je change de chaîne, il y a une seconde environ avec des carrés de couleur un peu partout comme si le décodage ramait. Est-ce normal ? Faudrait-il une version LibreElec pour Raspberry aussi  ?
Désolé pour le long message mais je voulais donner le maximum d'informations...

**Comment by aassif** [comment]
Il faut probablement ré-installer et re-valider sur le Freebox Server.
La version Raspberry Pi est déjà une version compilée pour LibreElec.

**Comment by chfarges** [comment]
J’ai essayé de réinstaller mais j’ai toujours le même message. Que faut-il faire au niveau du freebox server ? (L’ecran de mon freebox server ne marche plus mais le reste est parfaitement fonctionnel)

**Comment by aassif** [comment]
Il faut appuyer sur la flèche de droite :
https://www.free.fr/assistance/5054.html

**Comment by chfarges** [comment]
Super ! C'était bien ça ! J'ai appuyé sur la flèche de droite qui clignotait (sans rien voir sur l'écran) et ça a marché ! Merci beaucoup.
Dernier petit souci, j'ai bien accès aux chaines TNT sur mon raspberry mais pas sur le PC où je n'ai que les chaines IP.

**Comment by chfarges** [comment]
Bonjour ! À tout hasard, aurais-tu eu le temps de regarder pourquoi, sous libreelec, j’ai accès aux chaînes tnt sur mon Raspberry et pas sur mon PC ? (les chaînes IP sont bonnes sur les 2). Merci encore pour ton super addon !

**Comment by chfarges** [comment]
Désolé pour mon dernier message. Je viens de réessayer à l’instant et maintenant ça fonction. Bizarre mais bonne nouvelle ! PS : a quoi correspond le délai indiqué dans les réglages ? Merci !

**Comment by aassif** [comment]
Tant mieux si tout fonctionne :)

Le réglage "délai" correspond au temps entre chaque requête EPG.
Mes tests m'ont appris que la Freebox bloque le client si elles sont trop
fréquentes !

**Comment by aassif** [comment]
Tant mieux si tout fonctionne :)

Le réglage "délai" correspond au temps entre chaque requête EPG.
Mes tests m'ont appris que la Freebox bloque le client si elles sont trop
fréquentes !
