### ISSUE TITLE
Possible to cache ?

### ISSUE THREAD

**Issue by cdric61** [aassif/pvr.freebox#44]
Hello, i'm using last version for Leia on android tv box.
Is there a way to use buffering with freebox channels ?
They are considered as local network by kodi and don't use cache.
It could be better with a little buffering no ?

**Comment by aassif** [comment]
I might be wrong but I'm not sure I can set such a setting.
Currently, I only forward Kodi the URLs given by the Freebox Server.

**Comment by cdric61** [comment]
I think you're right.
Do you know witch one is chosen first when you select auto in source ? iptv or tnt ?
TNT seems to be local in the m3u file and iptv may not.

**Comment by aassif** [comment]
I can't remember. It's a server setting. I think it prefers DVB over IPTV.

Regarding the EPG data, it's not exactly XMLTV. It's JSON and I wish it were documented:
http://mafreebox.freebox.fr/api/v5/tv/epg/by_channel/uuid-webtv-404/1587403524
