### ISSUE TITLE
Spécifier l'adresse IP du serveur

### ISSUE THREAD

**Issue by Phigen** [aassif/pvr.freebox#46]
Bonjour,
Merci pour cet addon.
Chez moi, j'ai une installation de ma Freebox (mini) particulière qui fait que je ne peux pas accéder au serveur avec l'adresse "mafreebox.freebox.fr", par contre cela fonctionne avec l'adresse IP "192.168.0.254". Avec cette méthode, j'accède au serveur, je peux voir la TV depuis FreeboxOS... Mais votre addon ne fonctionne pas puisqu'il cherche "mafreebox.freebox.fr".
Serait-il possible d'avoir un réglage pour lui indiquer où trouver le serveur sur le réseau ?
J'ai essayer de fouiller dans les sources et j'ai vu que ce paramètre était présent dans "Freebox.cpp", j'ai essayé de le modifier mais ensuite j'ai plein d'erreurs lors de la compilation et c'est au-dessus de mes compétences, je ne sais pas programmer.
Merci et bonne journée.

**Comment by Phigen** [comment]
J'ai oublié : sous Linux64 + RPI4 et Kodi 18.6.

**Comment by aassif** [comment]
Bonsoir,
C'est assez facile à ajouter en tant que réglage.
Par contre, je ne comptais plus vraiment toucher à la branche Leia.
À vrai dire, le développement était en _standby_ en attendant la sortie de Matrix.
Je vais voir ce que je peux faire pour vous :)

**Comment by Phigen** [comment]
Merci, vraiment sympa.
Je suis obligé de garder Leia tant que Matrix n'est pas sorti en stable sous Libreelec pour mon RPI4.

**Comment by aassif** [comment]
https://github.com/aassif/pvr.freebox/releases/tag/2.0.2-Leia

**Comment by Phigen** [comment]
Encore merci pour le travail effectué.
J'ai testé, il y a du bon et du moins bon :
- le bon : je vois la liste des chaînes, je vois le guide EPG, je vois les enregistrements programmés et effectués depuis FreeboxOS, je peux programmer un enregistrement depuis pvr.freebox.
- le moins bon : je ne vois pas la TV.
Après réflexion, je pense que c'est lié au fichier "playlist.m3u" du Freebox serveur dans lequel les adresses sont codées en "rtsp://mafreebox.freebox.fr/". Ça ne dépend donc pas de l'addon.
Ce qui est étrange, c'est que je vois la TV depuis l'interface de FreeboxOS.
Dommage et encore merci.

**Comment by ninjaw** [comment]
>   Après réflexion, je pense que c'est lié au fichier "playlist.m3u" du Freebox serveur dans lequel les adresses sont codées en "rtsp://mafreebox.freebox.fr/". Ça ne dépend donc pas de l'addon.
>   Ce qui est étrange, c'est que je vois la TV depuis l'interface de FreeboxOS.
>   Dommage et encore merci.

Tout à fait, c'est très probable, cependant il doit être possible d'outrepasser ca en interne non aassif ?

**Comment by aassif** [comment]
@Phigen C'est ce que je craignais.
@ninjaw Il faudrait d'abord vérifier si ça fonctionne avec VLC.

**Comment by aassif** [comment]
De manière générale, je ne comprends pas comment FreeboxOS s'en sort.
Moi qui ai tout mon réseau local derrière un routeur branché à la Freebox, je suis obligé de passer par le VPN du Freebox Server pour pouvoir lire les flux tandis que ça marche en Flash !

**Comment by aassif** [comment]
@Phigen Avez-vous tenté d'ajouter un route réseau sur le client ?

**Comment by Phigen** [comment]
J'ai téléchargé le fichier playlist.m3u et j'ai changé toutes les références "mafreebox.freebox.fr" par "192.168.0.254" et ça passe dans VLC.
Il faudrait que l'addon fasse le changement au vol, mais je ne sais pas si c'est possible.
Ensuite, mes connaissances réseau sont limitées, donc pour les routes... il faudrait me guider.
Ma configuration, c'est un serveur mini4k + modem 4G.
La Freebox connectée sur le modem, tout sur le même réseau, le modem fait serveur DHCP, celui de la Freebox est éteint. Le player de la Freebox ne trouve pas le serveur. Le RPI4 (et tous les autres appareils) a accès au réseau local et à l'Internet par le modem 4G.

**Comment by aassif** [comment]
J'ai enquêté et j'ai l'impression que FreeboxOS utilise le flux HLS et non le RTSP.
À l'époque, j'avais fait quelques tests mais ils n'avaient pas été concluants.
Je vais renouveler l'expérience.

**Comment by Phigen** [comment]
Merci pour vos efforts.

**Comment by Fopossum** [comment]
Bonjour tout le monde.

Je viens de faire l'installation du plugin et j'apporte ma pierre à l'édifice. En tout état de cause j'aurai dû ouvrir un nouveau fil mais... Le problème semble être le même.

J'ai bien la liste des chaînes qui apparaît, les résumés, les « miniatures » aussi, mais impossible de lire un flux.

Environnement :
openelec x64 9.2.2 (donc Kodi Leïa) sur du vieux matos mais qui lit Neflix en 1080p
Freebox Revolution dernier firmware en date (option TV activée)
Setup simple, la Freebox est serveur DHCP et file des baux réservés aux machines du réseau. La box répond à mafreebox.freebox.fr (j'ai aussi testé par IP directe au cas où)
Je suis fibré et la TV est visible via le Freebox Player) 

Extrait du log de kodi lorsque tentative de regarder un flux (je mets pas le debug, parce qu'avec le rafraichissement des programmes, c'est trop long ; mais si besoin je peux augmenter le temps de poll de la freebox pour avoir des logs mais.... Vu les erreurs, pour moi, c'est pas un souci dans le fonctionnement en lui-même du plugin) : 

```
2020-04-30 19:10:27.069 T:140299718338752  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.freebox_204.pvr
2020-04-30 19:10:27.075 T:140298026829568  NOTICE: Creating InputStream
2020-04-30 19:10:27.076 T:140298026829568  NOTICE: Creating Demuxer
2020-04-30 19:10:57.142 T:140298026829568 WARNING: could not find codec parameters for rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=204&flavour=hd
2020-04-30 19:10:57.142 T:140298026829568   ERROR: OpenDemuxStream - Error creating demuxer
2020-04-30 19:10:57.142 T:140298026829568  NOTICE: CVideoPlayer::OnExit()
2020-04-30 19:10:57.449 T:140299718338752  NOTICE: CVideoPlayer::CloseFile()
2020-04-30 19:10:57.467 T:140299718338752  NOTICE: VideoPlayer: waiting for threads to exit
2020-04-30 19:10:57.467 T:140299718338752  NOTICE: VideoPlayer: finished waiting
```

Histoire de vérifier je teste depuis vlc sur une Fedora 31 à jour (avec les dépôts qui vont bien pour le multimedia) : 

```
Votre média d'entrée ne peut être ouvert:
VLC ne peut pas ouvrir « rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=844&flavour=ld ». Vérifier les messages du journal pour plus de détails.
```
Vais pas me laisser faire, voyons voir si plus de logs sont possibles avec mplayer (voir fichier joint vu qu'un peu verbeux mplayer est)

Spoiler alert, pas mieux.

[rtsp_mplayer_test_kodi_pvr.txt](https://github.com/aassif/pvr.freebox/files/4560070/rtsp_mplayer_test_kodi_pvr.txt)

(Je ne mets pas le log de tcpdump qui ne fait que révéler que mon laptop cause en IPv6 avec la box mais je peux le fournir, mais globalement, il n'apprend rien d'utile a priori).

Un telnet sur le port 554 de la box se connecte, pas de timeout (comportement attendu vu que je cause pas rtsp dans le texte).

```
telnet 192.168.1.254 554
Trying 192.168.1.254...
Connected to 192.168.1.254.
Escape character is '^]'.
^]
telnet> q
Connection closed.
```
De ce que je vois, l'adresse du flux est bien passée au décodeur vidéo par le plugin, c'est le décodeur vidéo qui ne retrouve pas ses petits et ce quelque soit le décodeur (vlc, mplayer ou libreelec).

Est-ce que ce sont les flux rtsp envoyés par la box qui sont pourris ? Est-ce que c'est autre chose ? J'ai pas les compétences en debug de flux vidéos pour me prononcer plus loin :-)



Aucune idée de si c'est limité aux Freebox Revolution ou pas.

**Comment by aassif** [comment]
Bonjour @Fopossum,
Ce problème ressemble beaucoup à https://github.com/aassif/pvr.freebox/issues/9,
à savoir un flux bloqué par un routeur tiers.
En revanche, si votre installation est basique, j'avoue être perdu.
Puisque VLC l'est également, je rejoins votre analyse selon laquelle l'_addon_ serait innocent ;)

**Comment by aassif** [comment]
Je vais compiler la version 2.0.3-Leia qui permet de tester les flux HLS, au cas où.

**Comment by aassif** [comment]
@Phigen L'adresse du serveur y est désormais remplacée à la volée !

**Comment by aassif** [comment]
https://github.com/aassif/pvr.freebox/releases/tag/2.0.3-Leia

**Comment by Fopossum** [comment]
Bonjour @aassif 

Cette nouvelle release semble améliorer les chose assez largement. J'ai désormais de l'image et du son. Par contre, j'ai ce qui ressemble a des problèmes de buffering maintenant ou de demuxage du flux. Kodi semble hésiter entre le flux 3D ou HD ou bas etc. Cela saute. 

Quelques erreurs encore dans les logs de kodi :

```
2020-05-01 11:51:23.256 T:140480277341952 WARNING: ActiveAE - large audio sync error: 2340.427983
2020-05-01 11:51:23.452 T:140478559504128  NOTICE: CVideoPlayerAudio::Process - stream stalled
2020-05-01 11:51:26.584 T:140478559504128   ERROR: CDVDAudio::AddPacketsRenderer - timeout adding data to renderer
2020-05-01 11:51:28.156 T:140480277341952 WARNING: ActiveAE - large audio sync error: 1245.012892
```

```
CCurlFile::Stat - Failed: Unsupported protocol(1) for http://192.168.1.254/api/v6/tv/img/channels/logos68x60/uuid-webtv-375.png
```

En fixant la qualité sur le flux, cela fonctionne mieux même si il semble y avoir du framedrop.

En tout cas merci pour le taf et j'espère que ça contribue aussi à la robustesse du plugin pour Matrix :)

EDIT : Le problème de buffering n'est peut-être pas lié, j'ai d'autres symptômes en lisant mes musiques en local sur du NFS (et j'ai toujours pas compris d'où ça venait donc je commence à incriminer mon matériel qui n'est plus de toute première jeunesse) donc, à prendre en compte. Il est possible que cette release corrige effectivement le problème complètement. J'ai d'ailleurs commandé une Raspberry Pi 4 hier, je testerai de nouveau quand je l'aurai reçu (quand ça arrivera, confinement oblige).

**Comment by aassif** [comment]
Je n'avais pas remarqué la 1re fois mais je constate que votre box a pour IP 192.168.1.254.
Est-elle bien en mode routeur ? N'y a-t-il aucun équipement intermédiaire ?

Concernant les saccades, seriez-vous passé au mode HLS ?

**Comment by Fopossum** [comment]
La box est en mode routeur tout à fait classique. Aucun équipement intermédaire autre qu'un switch gigabit.

Et HLS bah a priori oui puisque dernière version du plugin. Mais comme dit dans l'édition, c'est p'tet mon matériel qui est en cause là. Faut que je le teste pour être sûr.

**Comment by aassif** [comment]
HLS est désormais disponible dans les réglages mais c'est RTSP par défaut.

**Comment by Fopossum** [comment]
Même comportement, RTSP ou HLS selectionné, du buffering, mais là, je suis vraiment pas sûr que ça soit pas mon matos qui aide pas au debug ^_ ^

**Comment by Fopossum** [comment]
ifconfig m'annonce des erreurs. Il est fort possile qu'un câble, que le switch ou même le port RJ45 du HTPC (voire une combinaison des 3) soit en train de rendre l'âme ce qui serait cohérent avec les symptômes que j'ai par ailleurs.

Va falloir pousser les meubles pour vérifier le câblage.....

**Comment by Phigen** [comment]
Chez moi, ça fonctionne plutôt bien, avec ces réglages : RTSP (HLS très saccadé), IPTV (puisque le player n'est pas accessible), qualité basse ou standard (ADSL très mauvais, c'est pour cela que j'ai un modem 4G).
Par contre, quelques chaînes ne sont pas accessibles : France 5, C8, C News, C Star, Gulli, France O,... et d'autres.
Autre étrangeté, si je paramètre sur qualité "Auto", je n'arrive pas à me connecter.
Aurais-tu (j'ose), une idée d'installation pour que Box, Player et Modem arrivent à vivre ensemble et que tout soit accessible depuis les périphériques ?
Merci

**Comment by aassif** [comment]
Le débit est peut-être insuffisant pour les chaînes manquantes.
De mémoire, le mode "auto" sélectionne la meilleure qualité proposée.
En présence d'un débit faible, je pense qu'il faut donc forcer le niveau de qualité.

Enfin, le flux TV arrivant par la box, il faudrait une agrégation 4G mais je ne suis pas là pour vendre des Freebox Delta ;)

**Comment by Phigen** [comment]
Je ne suis pas sûr que ce soit un problème de débit pour les chaînes absentes, j'ai testé en bas débit, et c'est pareil.

**Comment by Phigen** [comment]
Par contre, je n'ai pas réussi à faire fonctionner la version PC. Je vois le guide et la liste des chaînes, mais pas la TV.

**Comment by Phigen** [comment]
Aujourd'hui, ça fonctionne aussi sur le PC et certaines chaînes (pas toutes) qui n'étaient pas accessibles le sont devenues. Je pense que ce manque de stabilité vient plus du serveur que de l'addon.

**Comment by Phigen** [comment]
J'ai passé la journée de vendredi à jouer avec les câbles et les réglages de la box et du modem 4G afin que box, modem et player acceptent de dialoguer ensemble, mais impossible. Si je veux le player avec la TNT, je ne peux pas avoir le modem 4G et inversement. Je n'ai sûrement pas les connaissances nécessaires. En dehors, du réglage de l'IP, le réseau, pour moi, c'est de la magie !

**Comment by Phigen** [comment]
Est-ce que ces améliorations seront intégrées à la version pour Kodi 19 ?

**Comment by aassif** [comment]
Elles le sont déjà ;)

**Comment by Phigen** [comment]
Merci.
