### ISSUE TITLE
2 sources de flux: pb sur le guide

### ISSUE THREAD

**Issue by cdric61** [aassif/pvr.freebox#47]
Bonjour,

j'utilise votre plugin pour toutes les chaines Freebox accessibles et l'IPTV de catchupTVandmore pour celles qui n'y sont pas (TF1 et M6 par exemple). 
Ca cohabite très bien sauf pour le guide TV où les chaines de catch up ne trouve pas le guide même spécifié dans le module.
J'ai l'impression que le guide freebox est pris systématiquement.
Avez vous déjà vu ce cas ?
On peut attaque l'xmltv de free directement ?
(Merci pour votre plugin, il est top !)

**Comment by aassif** [comment]
Merci pour votre enthousiasme !

Je n'ai pas effectué de tests avec plusieurs clients PVR mais je crois que chacun est responsable des chaînes qu'il propose.
Les deux sont donc censés pouvoir cohabiter.

Une solution bancale serait de réactiver les chaînes non disponibles sur la Freebox.
Cela permettrait de récupérer le guide des programmes mais toute action sur celui-ci dirigerait fatalement vers la chaîne du PVR Freebox.

**Comment by cdric61** [comment]
Quand on utilise un développement tous les jour, on peut être un minimum enthousiaste !
Ce que je constate:
- si j'active le guide sur TF1 de catchup ce sont les infos de France 4 qui s'affichent, donc je l'ai coupé
j'aimerai bien tester votre solution bancale :-). Avoir le guide même sans pouvoir interagir serait top.
Comment je peux faire pour réactiver ces chaines ?

**Comment by aassif** [comment]
C'est un paramètre de Kodi.
Consultez la page "TNT" du [wiki](https://github.com/aassif/pvr.freebox/wiki/) :)

**Comment by cdric61** [comment]
Ah oui... ce n'est pas ce que j'avais compris.
En effet c'est tres bancal.
Donc non j'ai déjà essayé.
C'est bizarre quand même que sur tf1 on ait le programme de france 4.
Je ne comprends pas.

**Comment by cdric61** [comment]
Et dans le gestionnaire de chaîne, le choix de la source du guide ne contient que "Client" alors qu'il devrait y avoir 2 choix normalement. Non ?

**Comment by aassif** [comment]
Au sein d'un client PVR, chaque chaîne possède un identifiant "unique".
Les deux chaînes des deux clients utilisent peut-être le même identifiant.
