### ISSUE TITLE
ajouts dans wiki

### ISSUE THREAD

**Issue by ninjaw** [aassif/pvr.freebox#48]
Quelques suggestions à mettre en wiki ? (tapé par moi pour l'occasion) :

**La TNT obligatoire pour TF1, M6 et Canal+**
La freebox rev/mini4k grâce a un astucieux service de streaming de TNT, appelée option multiposte,  permet de s'affranchir des limites imposées par les grands groupes privés (tf1, m6, canal+). Il est donc nécessaire de relier la box à la TNT, si vous voulez voir ces chaines apparaître sur Kodi, contrairement à une utilisation classique, au sein de la freebox player, qui, elle, peut s'en passer.

**Qualité du flux TNT**
La TNT est reliée à la freebox player. Bien sur il faut d'abord s'assurer qu'elle soit complète dans la section dédiée du player avant de les voir apparaître sur Kodi. De fait, cela ne peut marcher si la player n'est pas en veille partielle, on ne peut pas l'éteindre. De même, pour bénéficier d'une bonne qualité de flux, il est essentiel d'avoir une bonne qualité de réseau local entre les deux freebox, à savoir: un câble réseau. Si vous reliez les deux freebox avec leur câble ethernet, assurez vous d'avoir complètement coupé le CPL, sinon ca n'aura aucun effet. Oui: en fonctionnement optimal, les deux freeplugs doivent clignoter en rouge.

**TNT sans freebox player**
Plus rare et méconnu, avec la sortie de freebox os3.0 en 2014, il serait possible de brancher certaines clef TNT usb, sur la server, et donc de s'affranchir complètement d'une freebox player. Bien sur, cela ne permet pas de s'affranchir de payer l'option TV sur certains abonnements TV : pour avoir la TNT, ou même le multiposte TV,  il faut obligatoirement un forfait incluant la TV.

**Les chaines de radio sur freebox rev/mini4k** 
Le service radio existe mais n'a jamais été publié sur l'XML privé de la fbx. Il faut donc trouver tout seul les URL, Certain freenautes les ont récupéré des flux de l'ancienne freebox HD. pvr.freebox ne les prend pas en charge, puisque la freebox ne permet pas d'y accéder autrement qu'en la forçant.

**BUG freebox rev/mini4k de la TNT**
Pour diverses raisons, il arrive que la freebox ne présente plus la TNT sur son XML privé, alors qu'on les voit normalement dans le freebox player, mais donc qu'on ne les voit plus dans Kodi. C'est un bug qui n'a jamais été corrigé, il faut relancer la freebox server, puis relancer la recherche de chaines dans Kodi. Pour réinitialiser la freebox server correctement, on conseille de laisser une chaine de TNT affichée sur le player pendant qu'on reboot le server (cela n'a pas d'effet sur la TNT qui est programmée pour continuer d'afficher la TNT en cas de panne internet jusqu’à l’extinction). Il faut ensuite les relancer dans les paramètres de Kodi : Paramètres > Enregistreur / TV > Général > Gestionnaire de chaînes.

**Comment by ninjaw** [comment]
je pense à d'autres :

**Aspect ratio 4/3**
La TNT full HD peut être en 1440x au lieu de 1920x, si vous avez un affichage 4/3 au lieu de 16/9 sur vos enregistrements, pensez à vérifier l'option  Params/Media/Videos/Extraire les infos des fichiers (comme l'aspect ratio).
Il est aussi possible de forcer le 16/9 sur toutes les vidéos ici : Paramètres/Paramètres vidéo/Type de vue/Étirement 16:9, puis Prédéfinir ainsi pour tout média.

**Reseau local windows samba SMB**
Si vous ne pouvez pas acceder au reseau local de la freebox rev/mini4k, c'est peut être à cause de son âge avancé, vous pouvez forcer dans Kodi la version 1 du SMB, et uniquement le 1, la seule version que connait la freebox: Paramètres / Services / Smb 

**Autorisation freebox**
Le pvr.freebox nécessite de valider une autorisation sur l'écran de la freebox rev/mini4k pour fonctionner, en cas de bug d'affichage, essayez de relancer le plugin ou simplement de valider en appuyant sur le bouton tactile droite sur la freebox.
https://ninjaw.files.wordpress.com/2019/02/20190120_142241.jpg?w=768

**Comment by ninjaw** [comment]
J'ai pu transcrire tout ca moi meme dans le wiki, merci !

**Comment by aassif** [comment]
Merci pour toutes ces contributions !

Par contre, et je parle en connaissance de cause, la Freebox Delta est compatible :)
Il faut peut-être aussi clarifier le fait que seul le Player est acheté, tandis que le Server, qui fait office de NAS, est toujours en location.

Je peux m'en charger si tu veux mais j'ai l'impression que tu es bien lancé ;)

**Comment by ninjaw** [comment]
Ok j'ai clarifié l'avis un peu rapide et negatif sur la delta. Zut alors j'avais trouvé rien du tout sur le multiposte delta... je suppose que la one est aussi compatible. Arf faut clarifier le reste du wiki tres acces sur la revolution. La TNT est toujours assurée par la player ? ou les deux ? sur la delta ?

**Comment by aassif** [comment]
Je n'ai pas d'antenne TNT donc je ne peux rien affirmer mais il y a bien une prise sur le Player Devialet.
Il y a de fortes chances que la Freebox One fonctionne également.
En ce qui concerne la Freebox Delta S, et cela semblerait logique, j'ai la forte impression que le multiposte ne fait pas partie de l'offre.
