### ISSUE TITLE
recalbox installaion issue

### ISSUE THREAD

**Issue by tikismoke** [aassif/pvr.freebox#5]
Impossible de l'installer sur la dernière version de recalbox (6.0-DragonBlaze) sur un pi3.

Il me dit qu'il manque:
kodi.binary.global.gui version="5.12.0"

**Comment by ninjaw** [comment]
Le plugin est réservé à Kodi 18, en tout cas pour le moment.

**Comment by tikismoke** [comment]
Ha mince :(
je n'avais pas vue que c'était seuluement v17.6 qu'ils avaient implémenter dans la derniere recalbox.

Plusq qu'a croiser les doigts sur l'avancement de ton projet ou de recalbox :)

**Comment by ninjaw** [comment]
D'un point de vue recalbox ils n'attendent que la mise a disposition de la version speciale de Kodi qu'ils utilisent
