### ISSUE TITLE
Installation ubuntu18.04

### ISSUE THREAD

**Issue by Hatsumi-FR** [aassif/pvr.freebox#54]
Bonjour,

En suivant le tutoriel suivant "https://github.com/aassif/pvr.freebox/wiki/(FR)-Compilation" je rencontre un problème lors de la commande cmake. Cmake me retourne l'erreur suivante : 

CMake Error: The source directory "/home/hatsumi/pvr.freebox/ /home/hatsumi/kodi/cmake/addons" does not exist.

**Comment by aassif** [comment]
Bonjour,

Il semble y avoir un problème dans votre chemin.
Avez-vous bien respecté toutes les étapes ?

Si vous voulez une version Ubuntu, je vous conseille d'essayer les _nightlies_.
Vous aurez alors accès au plugin directement via le PPA officiel.

**Comment by jmlecomte59** [comment]
J'ai eu le même problème avec Ubuntu 20.04 et ça vient du "copier-coller" qui introduit des caracteres pas terribles. En les enlevant manuellement, l'instruction s’exécute normalement.
