### ISSUE TITLE
Ajouter une note pour OSMC

### ISSUE THREAD

**Issue by denics** [aassif/pvr.freebox#56]
Bonjour, avant tout super merci pour ce plugin pvr.

j'utilise OSMC et la derniere version de Leia pour libreelec fonctionne magnifiquement ici aussi. Il faudrait le documenter quelque part. 

Aussi il faudrait documenter quelque part les notes dans la issue #14 , car il y a beaucoup de monde qui utiliser la freebox en mode bridge et eux (free) n'a pas de doc sur ca. Pour ma part ca fait depuis 2014 que j'outlise le mode bridge, depuis que j'ai vu que le service technique de free peut se connecter sur la freebox en "remote"!!! depuis j'ai un freebox mini 4k en mode bridge et un openwrt qui fait son travail comme il faut.

**Comment by ninjaw** [comment]
Pour OSMC c'est implicite, de la meme maniere pvrfreebox marche aussi desormais sur retropie et batocera....
La issue #14 n'est pas assez clair pour un post wiki, je ne comprend pas pourquoi on parle de paquet à installer alors que l'on est dans un environnement libreelec ? essayez de rediger un truc e je l'insererais dans le wiki

**Comment by aassif** [comment]
Ce sont des paquets OpenWRT à installer sur le routeur, non ?

**Comment by ninjaw** [comment]
ha ok !

**Comment by denics** [comment]
biensur. Je n'osait pas le dire. Je vais faire une guide avec mes notes pour l'inclure dans le wiki. En revanche il ne faut jamais trop faire confiance à "l'implicite" :) 
Peut etre une ligne ou une matrix dans le readme ce serait peut être bienvenue.

**Comment by ninjaw** [comment]
Moui ? vraiment pas sur, je viens de rajouter ca dans le readme qui me parait bien plus complet et pertinent :
Compatible Kodi 17 sur PI, android, androidTV et linux X64, sera intégré toutes plate formes dans Kodi 18

**Comment by ninjaw** [comment]
il me semble que ce soit libreelec, omsc, retropie ou batocera, l'idée est toujours la même : avoir un kodi 17 sur un pi

**Comment by denics** [comment]
Super. Ma suggestion est basée sur le fait que la release s'appelle xxx_libreelec_xxx . Un utilisateur qui ne connais pas trop (moi) y pense plusieurs fois avant de l'installer dans son osmc :)

**Comment by ninjaw** [comment]
ha mais tout à fait ! ca peut se changer aassif ? (d'aillleurs c'est rigolo j'avais eu le probleme inverse avec un plugin des boutons nespicase+)

**Comment by denics** [comment]
du coup, ce serait aussi sympa d'avoir la release pour la dérniers versions Leia - 2.0.4

**Comment by aassif** [comment]
Je ne suis pas super motivé pour renommer les fichiers pour la simple et bonne raison qu'ils ont été compilés avec LibreELEC.
Tant mieux s'ils fonctionnent pour d'autres distribs mais on n'est pas à l'abri d'éventuelles incompatibilités.
Je serais donc plutôt en faveur de l'ajout d'une table de compatibilité.

À vrai dire, Matrix arrivant à grands pas, je ne proposerai bientôt plus aucune version compilée et toutes ces questions deviendront caduques.

L'_addon_ est déjà dispo sur les repos ainsi que dans les distribs proposant la version alpha :
https://mirrors.kodi.tv/addons/matrix/
https://forum.kodi.tv/showthread.php?tid=343068&pid=2952977#pid2952977
https://discourse.osmc.tv/t/kodi-19-matrix-nightly-builds-for-raspberry-pi/79407/259

**Comment by aassif** [comment]
> du coup, ce serait aussi sympa d'avoir la release pour la dérniers versions Leia - 2.0.4

Je peux relancer des _builds_ mais, franchment, le _fix_ est anecdotique.

**Comment by aassif** [comment]
> Compatible Kodi 17 sur PI, android, androidTV et linux X64, sera intégré toutes plate formes dans Kodi 18

Leia, c'est Kodi 18 ;)

**Comment by aassif** [comment]
Du coup, j'ai déporté la modif sur une nouvelle page "[Compatibilité](https://github.com/aassif/pvr.freebox/wiki/%28FR%29-Compatibilit%C3%A9)".

Je préfère laisser le `README` aussi sommaire que possible et ne pas mélanger les deux niveaux de compatibilité : le modèle de Freebox et l'OS sous lequel tourne Kodi.

**Comment by aassif** [comment]
@ninjaw J'espère que cela te convient.

**Comment by ninjaw** [comment]
oups le temps passe vite on est déjà sur 18. Oui c'est tres bien comme ça. Je t’avouerais que pour moi kodi 19 est tres obscur, du coup je testerais bien au moins sur windows puisque c nouveau, mais je ne vois meme pas de DL dans tes liens...
Sinon quitte a faire une page wiki on peut bien y rajouter un chapitre sur les OS non ?

**Comment by aassif** [comment]
> mais je ne vois meme pas de DL dans tes liens...

Il y a le lien pour LibreELEC.
Pour OSMC, j'ignore quelle est la procédure.
Enfin, pour Windows, tu peux trouver un installeur ici :
http://mirrors.kodi.tv/nightlies/windows/win64/master/

> Sinon quitte a faire une page wiki on peut bien y rajouter un chapitre sur les OS non ?

C'est justement le but de cette page "[Compatibilité](https://github.com/aassif/pvr.freebox/wiki/(FR)-Compatibilit%C3%A9)".
Peut-être son titre n'est-il pas adapté ?

**Comment by ninjaw** [comment]
non c tres bien, je viens d'essayer sur windows ouah ca marche !
