### ISSUE TITLE
Installation sur kodi Leia librelec pi4

### ISSUE THREAD

**Issue by Jonathanr67** [aassif/pvr.freebox#57]
Bonjour je tente en vain d'installer le zip sur une distribution librelec Leia sur un pi 4. J'ai un message d'erreur échec de l'installation à chaque fois...
Avez vous une solution à proposer.? (L'option source inconnues est bien activée dans les options.)

Merci

**Comment by aassif** [comment]
Quels fichiers avez-vous essayés ?

**Comment by Jonathanr67** [comment]
J'ai finalement réussi à installer l'addon

Avec le fichier :
 pvr.freebox-libreelec9.2-rpi4.zip 83.4 KB :

J'ai par contre quelques bug quand j'essaie de regarder un enregistrement
