### ISSUE TITLE
Freebox n'emettera plus du tout la TNT 

### ISSUE THREAD

**Issue by ninjaw** [aassif/pvr.freebox#60]
Deja que la pop player, declarée compatible avec toutes les freebox, est incapable de gerer les enregistrements sur disque dur, on vient d'apprendre une tres mauvaise nouvelle : c'est encore tres frais, mais freebox os pourrait encore enregistrer la tnt sur disque dur, contrairement au pop player, mais... n'emettera plus jamais la TNT en multiposte : 

https://dev.freebox.fr/bugs/task/31122

**Comment by aassif** [comment]
À en croire ce qui est annoncé sur le _bugtracker_, c'est une limitation technique du Player Pop.
Dommage cependant que seul le plus onéreux des deux _players_ en soit désormais capable.

**Comment by ninjaw** [comment]
Je viens de recevoir et tester la bete (le serveur). C'est un peu la merde, le multiposte -hors TNT- et le guide et le message de validation fonctionnent toujours, mais les enregistrements semblent bien buggés:
-Sur kodi player pop androitv, enregistrement en erreur et liste vide
-Sur pc alpha et pi4, liste enregistrement ok mais lecture semble peu fonctionnelle (vitesse, erreur), acceptation d'enregistrement depuis kodi ok mais aucun resultat concret sur le disque dur et le freebox os.

De plus, le lecteur pop etant la grosse merde annoncée, aucun moyen de savoir si on regarde la tnt ou non. Mon scan se passe bien mais coté serveur il semblerait qu'il n'y ait absolument aucune TNT de fonctionnelle en enregistrement.

Autre info, je viens de lire que la fonction "clef usb sur serveur" ne fonctionen plus sur delta et probablement plusn on plus sur pop... vu tout ce qu'il manque...

**Comment by ninjaw** [comment]
premiere maj de bugs pour la pop, peut etre une amelioration du coté des enregistrements que j'avais testé comme peu fonctionnel ? je teste ce soir, tjrs rien sur la terrible absence d'informations et menu TNT, et tjrs aucun enregistrement TNT reussi :
https://dev.freebox.fr/blog/?p=10230
```
Correction du problème Rash Player Error DrmSessionManagerError Failed to open session
Correction d’un crash lors de la lecture d’un flux TV
Meilleure gestion des TV ne supportant pas la sécurisation HDCP
Correction d’un crash lors de la programmation d’un enregistrement
Correction d’un bug de prise en compte de la date lors de la programmation d’enregistrement manuel
Ajout d’informations sur les écrans d’enregistrement lors d’un live
Prise en compte du changement de nom de profil après édition
```

**Comment by aassif** [comment]
Puisque l'antenne est sur le _player_, et tant qu'il n'est pas en mesure de retransmettre le flux TNT, je doute qu'on puisse un jour enregistrer la TNT sur le serveur.

**Comment by ninjaw** [comment]
Hein ? ha mais je suis le seul a m'en plaindre, j'ai harcelé plusieurs freenautes qui m'ont confirmé que le pop server enregistrait toujours la TNT en format libre. C'est pour ca que j'aimerais bien y arriver.
ps: ce que je vais tester ce soir n'a rien a voir bien sur, je vais voir si les conneries corrigées ce jour provoquaient bien les diverses erreurs depuis kodi, du genre absence de resultat sur l'enregistrement live alors que kodi pense que ca marche. Quoique l'on puisse supposer que ca pourrait vaguement aussi corriger la TNT.

**Comment by ninjaw** [comment]
bon j'ai fais des tests, on peut dire que les enregistrements depuis librelec rp4 fonctionnent.... en fait ya des choses bizarres, la lecture est lente a demarrer, ya une lecture rapide des fois a moins de changer de langues, bizarement si on enregistre puis on reclique, l'enregistrement disparaît immediatement. j'ai reussi a programmer sur rpi4, forcer l'arret sur freebox os, relire sur rpi4.
ca me parrait bien moins propre qu'avec la mini4k, mais au moins ca marche.
J'ai aussi testé toutes les solutions de tnt possibles et imaginable, aucun fichier obtenu, que ce soit ouvert ou fermé, dans chaque mode et chaque qualité...
ps: pvr refuse de s'activer sur la alpha1, pb de version

**Comment by Jez59** [comment]
Bonjour,

Pour les chaines TNT, j'ai également étudié la question. 
J'ai acheté une clé tnt pour mettre au cul de la Freebox server, mais ne captant pas grand chose (car pas de prise antenne dans mon local technique), j'ai abandonné l'idée.

J'ai trouvé une autre astuce :

J'ai installé Catch up tv and more. On peut lire les chaines des groupes TF1 et M6 en IPTV (bon il y a un bug sur les chaines du groupe M6 en ce moment, mais c'est un bug connu coté dev).
J'ai récupéré le M3U des chaines françaises installé par Catchup TV & More et je n'ai gardé QUE les chaines du groupe TF1 et M6 que j'ai collé dans un fichier .M3U à moi.

Dans l'extension PVR Simple IPTV client, j'ai indiqué mon fichier M3U.

Résultat : dans la section TV de Kodi, on a la liste des chaines de l'extension PVR Freebox et PVR Simple IPTV qui se mélangent (l'ordre est pas top, mais c'est explicable, car on a 2 fichiers M3U en "conflit").

=> Les chaines du groupe TF1 et M6 sont lues par la méthode Catchup TV & More
=> Toutes les autres chaines grace à l'extension PVR Freebox

En espérant que ca puisse aider certains utilisateurs :)
@++
Tom

**Comment by ninjaw** [comment]
Merci d'avoir donné une astuce hors pvr pour contrer free, je la connaissais déjà pour l'avoir mis sur mon blog, avec en plus un outil d'enregistrement sur tf1.
Pour conclure j'ai une petite info en plus:
-La freebox rev/mini4k retransmettent la TNT depuis la player OU la server avec certaines clef, l'enregistrent, et la rebalance sur le multiposte/pvr.freebox
-La freebox pop ne retransmettra plus jamais la TNT en multiposte, ET n'accepte plus de clef usb tnt sur le serveur non plus (sources officielles) malgré la presence du meme freebox os que la rev. Pour moi, elle n'enregistre plus non plus la TNT en reseau local, même si certains rigolos ont dit que si.
-La freebox delta enregistre et retransmet bien la TNT, par contre, officiellement elle n'accepte pas de clef usb tnt sur le server.
