### ISSUE TITLE
Pas d'icônes de chaines avec la version 2.01b-Leila Android 64bits

### ISSUE THREAD

**Issue by lmaiaux** [aassif/pvr.freebox#61]
Bonjour,

Super boulot, merci !

Je n'ai pas les icônes des chaines (sur tablette et smartphone Samsung).
Une idée d'ou vient le problème ou d'une façon de forcer la récupération des icônes ?

Merci

**Comment by ninjaw** [comment]
Tout est auto, pas d'options. Merci de préciser la freebox.

**Comment by lmaiaux** [comment]
Freebox Revolution en mode routeur.

**Comment by ninjaw** [comment]
Merci cela peut être un processus automatique lent. Je me sers peu d'Android, mais mon dernier test a même l Android de la pop avait bien les icônes. Avez vous les images des films du coup ?

**Comment by lmaiaux** [comment]
Non aucune image, ni dans le guide, ni dans les enregistrements.
Que veux-tu dire par "processus automatique lent" ?
Au demarrage de Kodi, le PVR indique tres rapidement "902 chaines chargees" (peut etre rapidement parceque les images ne sont pas chargees)

**Comment by aassif** [comment]
Bonjour !

Le message "902 chaînes chargées" indique que la liste des chaînes a été analysée.
Cependant, dans cette liste de chaînes, seuls les _chemins_ des logos sont récupérés et transmis à Kodi.
C'est Kodi lui-même qui va récupérer chaque image lorsqu'il en a besoin.
Il en va de même pour le guide des programmes.

Je suppose donc qu'il y a un problème de chemin de fichier.
Qu'obtenez-vous en chargeant l'URL [`http://mafreebox.freebox.fr/api/v5/tv/channels`](http://mafreebox.freebox.fr/api/v5/tv/channels) ?
En particulier, pouvez-vous me donnez un exemple de `logo_url` ?

**Comment by lmaiaux** [comment]
Je vais verifier ce soir (je n'ai pas ma freebox sous la main).
N'est-ce pas plutot .../api/v6/tv/channels ? (comme indique dans Freebox.cpp ligne 745, de plus Revolution=v6)

Il y a peut-etre autre chose : je n'ai pas creee de bouquet personnel, or il semble qu'a la ligne 754 de Freebox.cpp, la fonction Freebox::ProcessChannel termine avant de finir son traitement dans ce cas (qui justement utilise logo_url ligne 855).

J'essaierai donc ce soir apres avoir creee un bouquet...

**Comment by aassif** [comment]
`v5` ou `v6`, cela devrait marcher. 
Inutile de créer un bouquet, le bouquet `freeboxtv` existe par défaut.

**Comment by lmaiaux** [comment]
Bonjour,

Avec mon smartphone Samsung:

- avec http://mafreebox.freebox.fr/api/v5/tv/channels, j'obtiens:
{"success":true,"result":{"uuid-webtv-404":{"uuid":"uuid-webtv-404","name":"TEVA","available":true,"logo_url":"\/api\/v8\/tv\/img\/channels\/logos68x60\/uuid-webtv-404.png","has_service":true,"short_name":"TEVA","has_abo":true},...}

- avec http://mafreebox.freebox.fr/api/v5/tv/img/channels/logos68x60/uuid-webtv-404.png, je vois bien le logo de TEVA

- en me connectant sur freebox os, je vois bien les icones des chaines tv.

Une idee ?

**Comment by lmaiaux** [comment]
Attention : mon message poste a supprime tous les "\" qui etaient devant les "/" dans le path de logo_url

**Comment by lmaiaux** [comment]
tous les antislashs :-)

**Comment by lmaiaux** [comment]
J'ai fait un autre essai avec la derniere nightly Matrix sur MacOS et le probleme est le meme.

En utilisant le mode debug de Kodi je vois ces lignes dans le log a chaque acces a l'url d'un logo (sans autre erreur avant ou apres):

2020-08-28 12:28:54.030 T:63169   DEBUG <general>: GetImageHash - unable to stat url http://mafreebox.freebox.fr/api/v8/tv/img/channels/logos68x60/uuid-webtv-201.png

En accedant a l'url telle qu'affichee dans le log (avec Chrome), je vois bien le logo.

Si je sauvegarde une image de logo sur mon DD local en en modifiant le path de l'icone de la chaine (dans les parametres du gestionnaire de chaines de Kodi), je vois bien le logo dans Kodi...
... mais evidemment je ne veux pas faire ca pour toutes les chaines de la freebox.

A n'y rien comprendre !!!

Ces precisions vous donnent-elles des idees ?

Serait-il possible que le path des logos soit incorrect a cause des "\\" que la freebox met devant les "/" dans les chaines logo_url et qu'ils ne soient pas acceptes par Kodi ? (dans ce cas il faudrait les supprimer avant des les fournir a Kodi)
- il se pourrait que ces "\\" ne soient pas visibles dans le log
- pourquoi cela n'arrive qu'a moi ?

**Comment by aassif** [comment]
Je n'ai pas l'occasion de regarder ça maintenant mais je peux essayer de répondre aux deux dernières questions :
- les antislashes n'y sont pour rien, ils sont dûs au format JSON ;
- aucune idée pour l'instant !

Les mêmes erreurs apparaissent-elles également dans le log Leia ?

**Comment by lmaiaux** [comment]
Oui, ce sont les mêmes erreurs dans le log Leia de ma tablette Android.

**Comment by aassif** [comment]
J'ai le même problème chez moi !
Apparemment, la Freebox ne retournerait plus les entêtes en question et répond par un 404 :
`curl -I http://mafreebox.freebox.fr/api/v8/tv/img/channels/logos68x60/uuid-webtv-201.png`

**Comment by aassif** [comment]
J'ai lancé une tâche sur le _bugtracker_ officiel :
[https://dev.freebox.fr/bugs/task/32183](https://dev.freebox.fr/bugs/task/32183)

**Comment by lmaiaux** [comment]
Ok, merci !

**Comment by aassif** [comment]
J'ai eu une réponse sur le bugtracker mais pas celle que j'attendais :laughing:
A priori, il faut que je cherche une autre piste !

**Comment by lmaiaux** [comment]
Je vois.
Leur reponse est etonnante car je suppose que quand tu l'as developpe, ca marchait.
Peut-etre que ca n'a jamais marche mais que ca ne retournait pas une erreur 404 avant (?)

Pour ma culture perso, qui fait une requete HEAD sur ces url d'images ? Kodi ou ton code ?
Une requete GET ne peut pas etre utilisee a la place ?

**Comment by aassif** [comment]
Je n'ai aucune idée de si la requête HEAD marchait ou non.
Par contre, c'était une piste intéressant puisque c'est ainsi que fonctionne `GetImageHash`.

D'autant plus que la 2.0.1b-Leia date de mars !
Soit ça vient de Kodi, soit ça vient de la Freebox.
Et comme le problème est apparu à la fois sur Leia et sur Matrix, je pencherais pour la Freebox.

Quelles versions de Kodi utilisez-vous ?
Quelle version de FreeboxOS ?
@ninjaw, ça marche toujours chez toi ?

**Comment by aassif** [comment]
> Pour ma culture perso, qui fait une requete HEAD sur ces url d'images ? Kodi ou ton code ?

Une requête `HEAD` demande les entêtes d'un fichier :
[https://developer.mozilla.org/fr/docs/Web/HTTP/M%C3%A9thode/HEAD](https://developer.mozilla.org/fr/docs/Web/HTTP/M%C3%A9thode/HEAD)

En général, pour connaître sa date de modif et, dans le cas d'un fichier binaire, sa taille.

**Comment by Jez59** [comment]
Bonjour,

Mon commentaire n'apportera certainement rien de nouveau, mais j'ai constaté le même problème avec une version 2.0.3-Leia installée sur un Raspberry pi 3b. Le slogos ont disparu du jour au lendemain.

Je l'ai installé fin juin de mémoire et les logo ont disparus cet été (fin juillet / début aout ? je ne me souviens plus trop).

J'ai une Freebox Delta pour info.

Bon courage pour ce bug !
Joli travail pour l'ensemble de ton oeuvre !

**Comment by ninjaw** [comment]
se pourrait il que ca ait un lien avec l'annonce du bugfix urgence 18.9 qui mentionne de nombreux pb de connexion http ? je n'ai encore ni librelec ni android en 18.9

**Comment by aassif** [comment]
Malheureusement, j'en doute car il y est fait mention d'un problème avec Cloudflare.

**Comment by ninjaw** [comment]
pourquoi ? cloudfare semble etre un partenaire qui fait proxy web pour kodi ? (pour simplifier)

**Comment by aassif** [comment]
Réponse courte : ça ne marche toujours par sur la _nightly_ Ubuntu.
Réponse longue : je ne pense pas que Cloudflare intervienne entre le serveur FreeboxTV et moi.

**Comment by aassif** [comment]
J'ai refait des tests et j'ai mis en place une solution temporaire :
les logos des chaînes sont désormais téléchargés localement et non plus à la volée par Kodi.

**Comment by aassif** [comment]
Reste à porter le _fix_ sur la branche Leia et, surtout, à recompiler toutes les _releases_ Leia :sob:

**Comment by ninjaw** [comment]
qu'en est il des screenshots ? je teste. Es tu en train de confirmer que le probleme ne viendrait pas de free ?

**Comment by aassif** [comment]
Les _screenshots_ ne marchent toujours plus.
Par contre, je ne peux pas me permettre de tout mettre en cache.

Vu que le problème touche Leia et Matrix, je pense que le problème vient de Free.
Ils ont dû changer quelque chose mais je ne vois pas quoi.
Peut-être y avait-il un problème chez Kodi qui ne se révèle que suite à cet éventuel changement.

**Comment by aassif** [comment]
@ninjaw Tu ne m'as jamais vraiment répondu : est-ce que ça marche chez toi ?

**Comment by ninjaw** [comment]
oui ca marche sur windows

**Comment by lmaiaux** [comment]
**@ninjaw** Avec quelle(s) Freebox(s)

**Comment by ninjaw** [comment]
ca fait 2 questions que je ne comprends pas ?? j'ai une freebox pop, pourquoi me demander ca ?

**Comment by aassif** [comment]
> oui ca marche sur windows

Avec une install fraîche ?

**Comment by ninjaw** [comment]
non ? une mise a joru automatique ? pourquoi, qu'est-ce qu'il se passe ?

**Comment by aassif** [comment]
> ca fait 2 questions que je ne comprends pas ?? j'ai une freebox pop, pourquoi me demander ca ?

Quel type de serveur ?

On te demande parce que ça marche chez toi et pas chez nous :)

**Comment by aassif** [comment]
Si tu es sous Windows 10, peux-tu essayer la commande suivante ?
`curl.exe -I http://mafreebox.freebox.fr/api/v8/tv/img/channels/logos68x60/uuid-webtv-201.png`

**Comment by ninjaw** [comment]
> > ca fait 2 questions que je ne comprends pas ?? j'ai une freebox pop, pourquoi me demander ca ?
> Quel type de serveur ?
> On te demande parce que ça marche chez toi et pas chez nous :)

Heu c'est un serveur pop classique, mais je ne comprend pas: tu as posté que tu avais patché le truc en cloturant le probleme ? du coup ben j'ai regardé et ca a bien fait ce que tu asvais prevu , si vous parlez des screenshots, ca ne marche pas, comme prevu ! PS: je serais chez moi ce soir

**Comment by aassif** [comment]
OK. Je demandais si ça marchait ou pas **avant** le _patch_.
Je n'étais pas certain que tu étais impacté par le _bug_.
Inutile de tenter le `curl` si c'était le cas.

**Comment by aassif** [comment]
J'ai rouvert à cause des miniatures de l'EPG.

**Comment by lmaiaux** [comment]
Tu as compris puisque tu as repondu :-)

Les questions servent a cerner d'ou vient le probleme.

Pour ma part, je pense que le probleme vient d'une modification vers mars 2019 dans l'API REST de la Freebox Revolution (celle que j'ai) mais qui ne concerne peut-etre pas la Pop (celle que ninjaw a)
Je pense que les requetes HEAD n'ont jamais marche (comme indique par Free) mais que ces requetes retournent desormais une erreur 404, ce qui conduit KODI a ne plus afficher les images.

Je pense que ces requetes HEAD sont utilisees pour savoir si une image mise en cache (par KODI) a change pour une meme URL (date, taille, ...) et donc si l'image doit etre relue pour mettre son cache a jour.

Je pense qu'avant (que la requete retourne 404), le cache etait interprete par KODI comme tout le temps a jour (pas de modification du contenu de l'image en fonction de l'URL) ou jamais a jour (relecture systematique affectant eventuellement les performances) mais que cela n'empechait pas la lecture et la visualisation des images...

Aassif, penses-tu qu'il soit possible d'introduire un wrapper (optionnel) entre ton module et la Freebox pour corriger les requetes HEAD (en les transformant en GET mais en retournant les messages/infos corrects du HEAD) ?

**Comment by ninjaw** [comment]
Ah ok. Oui j'avais le même problème sur toutes mes machines au même moment, contrairement à ce que j'ai pu dire.

**Comment by aassif** [comment]
> Aassif, penses-tu qu'il soit possible d'introduire un wrapper (optionnel) entre ton module et la Freebox pour corriger les requetes HEAD (en les transformant en GET mais en retournant les messages/infos corrects du HEAD) ?

Sur le papier, rien ne l'empêche mais adieu la simplicité d'utilisation !

**Comment by Jez59** [comment]
> 
> 
> Reste à porter le _fix_ sur la branche Leia et, surtout, à recompiler toutes les _releases_ Leia 😭

Merci :D Je reste au také pour installer la mise à jour dès qu'elle sera dispo !

**Comment by aassif** [comment]
@lmaiaux @Jez59 Quelles architectures vous faut-il ?

**Comment by Jez59** [comment]
> 
> 
> @lmaiaux @Jez59 Quelles architectures vous faut-il ?

Bonjour,

J'utilise Kodi Leia sur un Raspberry pi 3b

D'avance merci pour la compilation :)

**Comment by aassif** [comment]
LibreELEC ?
@lmaiaux ?

**Comment by aassif** [comment]
> J'utilise Kodi Leia sur un Raspberry pi 3b

LibreELEC ?

**Comment by Jez59** [comment]
> 
> 
> > J'utilise Kodi Leia sur un Raspberry pi 3b
> 
> LibreELEC ?

Oui

**Comment by aassif** [comment]
Je vais tenter ça ce week-end (LibreELEC 9.2.6).

Désolé de ne pas être super réactif en ce moment.
J'aimerais avoir plus de temps pour m'occuper du PVR.
Je ne désespère pas de trouver la cause réelle du problème !

**Comment by aassif** [comment]
Vu la [solution](5605206) que je viens de bricoler,
je persiste à croire que la première piste était la bonne et que Freebox OS a changé quelque chose !

J'altère les URL des images pour que Kodi ne fasse plus jamais de HEAD mais systématiquement du GET.
C'est pour moi la preuve que ce bug a été introduit par Free.

**Comment by aassif** [comment]
Vu la [solution](https://github.com/aassif/pvr.freebox/commit/560520678f08fd644dad14b6507a905ba4be8337) que je viens de bricoler,
je persiste à croire que la première piste était la bonne et que Freebox OS a changé quelque chose !

J'altère les URL des images pour que Kodi ne fasse plus jamais de `HEAD` mais systématiquement du `GET`.
C'est pour moi la preuve que ce bug a été introduit par Free.

**Comment by aassif** [comment]
Bonne nouvelle : j'ai lancé le _build_ RPi2 pour LibreELEC 9.2.6.
Mauvaise nouvelle : déjà plusieurs incompatibilités avec Ubuntu 20.10 (GCC 10).
J'ai surmonté facilement les soucis avec `binutils` et `p7zip` ; à voir ce qui suit...

**Comment by aassif** [comment]
[C'est bon !](https://github.com/aassif/pvr.freebox/releases/download/2.0.5-Leia/pvr.freebox-libreelec9.2.6-rpi2.zip)

**Comment by ninjaw** [comment]
sur le nouveau beta 1 windows j'ai retrouvé toutes les images !

**Comment by aassif** [comment]
C'est grâce au [nouveau fix](#issuecomment-731295946) :)

**Comment by Jez59** [comment]
> 
> 
> [C'est bon !](https://github.com/aassif/pvr.freebox/releases/download/2.0.5-Leia/pvr.freebox-libreelec9.2.6-rpi2.zip)

Testé et approuvé !

Icones OK !

**Comment by Jez59** [comment]
Je ne veux surtout pas faire le "lourd dingue", mais juste pour info, la qualité des icônes et des aperçus n'est pas TOP avec la dernière release. 
Ça fait très pixelisé dans l'interface KODI.

La méthode de récupération des aperçus permet d’accéder à plusieurs résolutions d'images (genre low, med, high ?) ?

**Comment by aassif** [comment]
À ma connaissance, il n'y a qu'une seule image disponible par chaîne.
Le Player Devialet semble en utiliser de meilleure qualité mais leurs URL me sont inconnues.
