### ISSUE TITLE
la lecture des enregistrements ne se lancent pas

### ISSUE THREAD

**Issue by Jez59** [aassif/pvr.freebox#63]
Bonjour,

J'utilise une version 2.0.3-Leia sur un Raspberry PI 3b. Freebox Delta Server.

Je vois sans problème la liste des enregistrements disponibles, ainsi que les programmations dans la section TV de Kodi.
Seulement, je n'arrive pas à lire les enregistrements.

Lorsque je tente de lancer la lecture d'un enregistrement, il ne se passe rien. (si j'accède via le réseau, directement sur Freebox server, je peux lancer les enregistrements disponibles depuis le disque)

Est ce que ce problème est connu ? Pourrais-je uploader des logs pour vous aider ? (si oui, merci de m'indiquer le PATH et le nom du fichier qui vous intéresse).

Bien cordialement
Tom

**Comment by ninjaw** [comment]
il y a des pb connus, récemment sur la pop j'ai du changer de langue pour avoir une lecture qui ne bug pas au point de couper de suite
Je confirme que le probleme de securité linux n'est toujours pas corrigé sur la pop serveur ! ca pourrait etre ca qui bloque touty acces de linux vers samba :  https://github.com/aassif/pvr.freebox/wiki/%28FR%29-Reseau-local-windows-samba-SMB

**Comment by Jez59** [comment]
J'ai tenté de forcer la version smbV1, mais ca ne change rien.

Dans la section TV de Kodi / Enregistrements : Je vois bien la liste des enregistrements.
Mais quand je tente de lancer une lecture => ca ne lance pas la lecture.

Si je vais manuellement, via un lecteur smb, dans le répertoire Enregistrement du freebox server, je vois la liste des enregistrements, et je peux lire les fichiers sans problème.

**Comment by aassif** [comment]
Pour ma part, mes _logs_ fourmillent de messages du type :
`unix_err:'16' error : 'Invalid argument'`

Je n'ai bien évidemment pas la moindre idée de quand date leur apparition.
Par contre, je sais que la lecture des enregistrements fonctionnait.

**Comment by aassif** [comment]
De mon côté, tout marche quand je force SMBv1.
Par contre, il faut bien mettre SMBv1 en version maximale _et_ minimale.
J'ai l'impression que la case "Utiliser la sécurité traditionnelle" n'a pas d'effet.

**Comment by Jez59** [comment]
Bonjour,

La dernière version (Dont le lien est dispo dans l'issue "Pas d'icônes de chaines avec la version 2.01b-Leila Android 64bits") corrige ce problème.
Tout fonctionne nikel maintenant !
