### ISSUE TITLE
Incompatible avec la dernière version Matrix (18.9.702)

### ISSUE THREAD

**Issue by gd71** [aassif/pvr.freebox#66]
Bonjour,
Vous êtes déjà certainement au courant mais dans le doute
L'extension est desactivée avec le message:
"l'extension n'est pas compatible avec cette version de kodi"
Kodi version : 19.0-ALPHA2 (18.9.702)
Plateformes ou le problème est constaté:
 - Ubuntu 20.04.1
 - Librelec 9.80 nightly

**Comment by ninjaw** [comment]
Oui je confirme l'appli a disparu depuis deux blogs/maj de kodi au sujet de la beta, je ne sais pa snon plus si c'est lié aux autres activités

**Comment by aassif** [comment]
Effectivement, j'avais oublié de faire la dernière _release_.

**Comment by aassif** [comment]
En même temps, je n'étais pas pressé vu toutes les fonctionnalités qui tombent en rade.

**Comment by ninjaw** [comment]
Ca va me permettre de restester ce soir windows 10 et la pop server voir si la réactivité a été maj. Je rappelle que pour moi la pop server marche a peu pret avec de droles de vitesses/option de lecture a forcer.
