### ISSUE TITLE
Installation de l'addon sur Kodi

### ISSUE THREAD

**Issue by hista** [aassif/pvr.freebox#67]
Bonjour,
j'essaie d'installer l'addon sur un Kodi 18.8 (sous debian sid).
J'ai téléchargé pvr.freebox-6.0.0-Matrix.zip sur https://codeload.github.com/aassif/pvr.freebox/zip/6.0.0-Matrix, 
puis tenté d'installer le zip depuis le manager d'addon de kodi, mais cela générère un message d'erreur disant que l'isntallation a échoué.
Est-ce bien la bonne façon de procéder ?

J'ai également un kodi sur une mibox 3 où tester l'installation.

**Comment by ninjaw** [comment]
18=leia 19=matrix
check plutot les exécutables ici : https://github.com/aassif/pvr.freebox/releases/tag/2.0.3-Leia
en plus la version matrix est desormais integrée dans la liste des PVR kodi

**Comment by aassif** [comment]
Merci @ninjaw !
Je suppose que l'installation s'est bien déroulée.
Je clos la question.
