### ISSUE TITLE
Pb Démarrage de l'enregistreur video a 0%

### ISSUE THREAD

**Issue by nounours6193** [aassif/pvr.freebox#68]
Bonjour, j'ai installé pvr.freebox 2.0.5 sur une version LibreELEC 9.2.6 pour raspberry pi 3b+ avec Kodi Leila 18.9, lorsque la page TV charge, j'ai un chargement avec "Démarrage de l'enregistreur video qui reste bloqué a 0% puis fini par laisser vide les chaines dans le groupe TV.
Ce qui est surprenant c'est en utilisant une autre microSD avec une installation Android lineage OS 15.1 et kodi de la même version et les même parametres réseau (SMBv1, Serveur WINS, WiFi), le problème n'existe pas et j'ai bien les 902 chaines trouvées

**Comment by aassif** [comment]
Bonjour,
Je suppose qu'il s'agit d'un Raspberry Pi 2/3.
S'agit-il d'une nouvelle installation ou d'une mise à jour ?
Pourriez-vous, s'il vous plaît, joindre un fichier de _log_ ?

**Comment by nounours6193** [comment]
C'est bien un raspberry 3b+ avec une nouvelle installation
Ou se trouve le repertoire de log de pvr.freebox sur la micro SD?

**Comment by aassif** [comment]
Désolé pour la réponse tardive :
`/storage/.kodi/temp/kodi.log`

**Comment by nounours6193** [comment]
Mon problème est résolu.  C'était à cause de mes 2 gateway sur mon réseau, il fallait que j'indique celle de la Freebox au raspberry. Par contre j'ai une question concernant les chaînes payantes dont j'ai souscrit à une offre en pack. Puis je les avoirs sur Kodi via le pvr ? Si oui comment est ce possible

**Comment by aassif** [comment]
Seules les chaînes disponibles en multiposte sont accessibles.
Ce n'est malheureusement pas le cas des chaînes payantes.
