### ISSUE TITLE
compilation (?inutile???) de tous les addons

### ISSUE THREAD

**Issue by dfrey** [aassif/pvr.freebox#70]
je me trompe peut etre mais la procedure de compilation indiqué recompile aussi tous les addons qui sont déjà dans kodi. Cela prend du temps, n'est il possible de compiler seulement cet addon? 
Alternativement, est-ce que on peut tout simplement copier pvr.freebox dans kodi/cmake/addons?

**Comment by aassif** [comment]
Normalement, la procédure ne compile que l'addon.
De toute façon, plus personne n'a besoin de le compiler maintenant que Kodi 19 est là.

**Comment by dfrey** [comment]
bonjour Assif, 
je suis en train de retester. Je suis nouveau à Kodi donc c'est peut etre ça le probleme. 
Test 1: 
Kodi installlé sur raspberry pi via apt
pour compiler l'addon j'avais besoin des sources par contre. 
Quand j'ai fait la procedure de compilation il a essayé de compiler touts les addons dans pvr.freebox/build et il a planté sur mrboom

Test 2
Kodi installé via sources
compilé, mais pas compilé les addons (je pensais que c'etait automatique) 
compilation de pvr.freebox il compile à nouveau tout les addons en plante sur mrboom

Test 3
la j'ai reinstallé Kodi via sources, compilé les addons dans le tree de kodi. 
En suite j'ai compilé pvr.freebox et il l'a l'aire de marcher, mais c'est en cours ;)

**Comment by aassif** [comment]
Vous vous compilez la vie à compiler Kodi !
Sur quelle archi êtes-vous ? PC ? Raspberry Pi ?

**Comment by aassif** [comment]
Vous vous compliquez la vie à compiler Kodi !
Sur quelle archi êtes-vous ? PC ? Raspberry Pi ?

**Comment by dfrey** [comment]
RPI4 RaspberryPi OS (ancien Raspbian) 

La seule raison pour la quelle j'ai recompilé Kodi est que les instructions ici: https://github.com/aassif/pvr.freebox/wiki/%28FR%29-Compilation

disent de cloner Kodi, et en suite en suivant les instruction sans recompiler kodi, j'ai eu la compilation de tous les addons (Test 1) qui a planté. ;)

**Comment by aassif** [comment]
Les instructions de compilation sont destinées à ceux qui veulent compiler ;)

L'_addon_ est dispo sur les _repos_ officiels.
Je ne sais pas ce qu'il en est pour Rasbperry Pi OS mais je serais très surpris que cela ne soit pas le cas.
Sur Ubuntu, le paquet s'appelle `kodi-pvr-freebox`.

**Comment by dfrey** [comment]
ah cool je ne savais pas ;) 
merci 

Davide Frey


www.coronasurveys.org

consultez notre carte du risque COVID-19: https://coronasurveys.org/data/

Aidez nous en répondant à nos sondages: 
- https://survey.coronasurveys.org/FR
- https://play.google.com/store/apps/details?id=org.coronasurveys.mobile
- https://apps.apple.com/fr/app/coronasurveys/id1514669450
