### ISSUE TITLE
Installation RPI 4 LibreElec

### ISSUE THREAD

**Issue by xsellier** [aassif/pvr.freebox#72]
Bonjour,

Tout d'abord merci pour ce repo merveilleux :dancers: 
Je voudrais savoir s'il vous était possible de fournir cet addon compilé pour RPi 4 pour LibreElec (c'est Kodi 18.9),
Ou alors un petit docker container qui permet de faire un build assez simplement
Ou alors un travis (ou github release) qui permet de générer un build.
Ou alors je ne trouve pas la derniere version.

Merci par avance!

J'ai vérifié le PVR est disponible pour Matrix mais pas pour Leia (pas encore du moins):
https://mirrors.kodi.tv/addons/matrix/

**Comment by ninjaw** [comment]
l'outil a été crée pour librelec... il est donc là https://github.com/aassif/pvr.freebox/releases/download/2.0.3-Leia/pvr.freebox-libreelec9.2-rpi4.zip
bon entre temps il a été travaillé pour être integré automatiquement dans 19, ce qui est le cas depuis les quelques jours ou Kodi 19 est sorti officiellement.

**Comment by xsellier** [comment]
Merci je teste ça, et je mets a jour ce ticket.

Ça marche nickel, merci pour ce plugin!

**Comment by aassif** [comment]
Bonjour !
Concernant LibreELEC sur RPi4, vous pouvez également utiliser les versions de test.
Elles sont plutôt stables et proposent la dernière version de l'_addon_ sur les _repos_ officiels.
https://test.libreelec.tv/

**Comment by xsellier** [comment]
Effectivement merci pour ce partage (la version actuelle marche très déjà)
