### ISSUE TITLE
Autorisation freebox

### ISSUE THREAD

**Issue by Redhill54** [aassif/pvr.freebox#77]
I have set up Kodi and the PVR Freebox TV PVR client , but Kodi sends me a repeated message

 "PVR Freebox TV  
Authorise Kodi on Freebox Server"

On the Freebox Server I can see no way to authorise Kodi on the Freebox.  

I can get Kodi to work with the NextPVR PVR Client to give me UK channels which I have legal access to through membership of the British TV club, so presume that my use of Kodi is working, but cannot see programmes on the French channels which I am entitled to as a paying Freebox customer from     mafreebox.freebox.fr

I have a new Freebox Server and Freebox Player.  

I am writing to you as I have tried to look everywhere for information and guidance on this, and asking here is my last resort.  

If you want me to translate this request into French, let me know and I will try to convey what my problem is.  

With thanks in advance

**Comment by ninjaw** [comment]
Did you check wiki first https://github.com/aassif/pvr.freebox/wiki/%28FR%29-Autorisation-freebox

**Comment by Redhill54** [comment]
Thanks for looking at this.  

I had already looked at the page you gave the link for about "Autorisation-freebox".  It covers earlier versions of the Freebox, but when I put my hand in front of the Freebox Server, and checked the messages using t he up and down buttons, I could not see any way to authorise Kodi.  

If I missed a way to do it, please let me know.  

Thanks again for your attention to my problem.

**Comment by aassif** [comment]
It should work regardless of the model.
If you missed it the first time, you need to delete Kodi in the [apps](http://mafreebox.freebox.fr/#Fbx.os.app.settings.Accounts) tab.
Then, the next time you start Kodi, keep an eye on the server.

**Comment by Redhill54** [comment]
Sorry to have to ask you for more details.  

You said that I need to "delete Kodi in the apps tab", and then keep an eye on the server.  

Where can I find or see the relevant apps tab? 

Where will I look to keep an eye on the server?  

 I have looked, but cannot see the tab or the server information, so have to ask for your advice.  

Thanks again for your help.

**Comment by aassif** [comment]
Sorry, I was quite busy this week.

When I said to "delete Kodi in the 'apps' tab", I meant in Freebox OS.
That's why I provided a link ;)

On the server, a message should appear as soon as you start Kodi.

**Comment by aassif** [comment]
@Redhill54 Can I close this issue?
