### ISSUE TITLE
Compilation - Pas de cible spécifiée

### ISSUE THREAD

**Issue by JulienAramino** [aassif/pvr.freebox#79]
Bonjour,
Savez vous comment corriger ce problème a la compilation ?
```
[ 90%] Performing forcebuild step for 'pvr.freebox'
Force build of pvr.freebox
[ 93%] Performing build step for 'pvr.freebox'
make[4]: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
make[3]: *** [CMakeFiles/pvr.freebox.dir/build.make:114 : pvr.freebox-prefix/src/pvr.freebox-stamp/pvr.freebox-build] Erreur 2
make[2]: *** [CMakeFiles/Makefile2:270 : CMakeFiles/pvr.freebox.dir/all] Erreur 2
make[1]: *** [CMakeFiles/Makefile2:304 : CMakeFiles/package-addons.dir/rule] Erreur 2
make: *** [Makefile:209 : package-addons] Erreur 2
```
Merci

**Comment by aassif** [comment]
Bonjour,

Pour quelle plateforme souhaitez-vous compiler l'_addon_ ?
Il est fort probable que celle-ci soit déjà disponible sur les _repos_ officiels.

La page [wiki](https://github.com/aassif/pvr.freebox/wiki/(FR)-Compilation) n'est pas à jour puisqu'il y est question de Leia et non de Matrix.
Les ajustements nécessaires sont néanmoins minimes :
- "19.1-Matrix" au lieu de "18.6-Leia" pour Kodi,
- "Matrix" au lieu de "Leia" pour pvr.freebox.

**Comment by JulienAramino** [comment]
Bonjour,

J'ai essayer de compiler avec ubuntu 20.04 avec Kodi Matrix.
Je n'ai pas trouvé de zip adéquate dans ce repo (pour Matrix) ou alors je ne sais pas quoi choisir.

J'avais changé les noms dans la commande. (Mais pour Kodi j'avais mis juste Matrix et non 19.1-Matrix et pour pvr.freebox 6.1.4-Matrix).

Quand vous dîtes les repos officielles, parlez vous via l'interface de Kodi? Si oui je vais googler un peu.

Merci

PS: j'ai essayé avec les branches conseillées mais Idem.

**Comment by JulienAramino** [comment]
Bonjour,

Hélas je ne trouve aucune référence a pvr.freebox sur le repo officielle d'Addon sur kodi.

**Comment by aassif** [comment]
`kodi-pvr-freebox`

**Comment by aassif** [comment]
[https://kodi.wiki/view/Ubuntu_PVR_add-ons](https://kodi.wiki/view/Ubuntu_PVR_add-ons)

**Comment by JulienAramino** [comment]
Merci beaucoup

**Comment by protopyte** [comment]
```
git clone -b 19.1-Matrix https://github.com/xbmc/xbmc.git kodi
git clone -b Matrix https://github.com/aassif/pvr.freebox.git
PREFIX=$PWD
cd pvr.freebox
mkdir build
cd build
cmake -DADDONS_TO_BUILD=pvr.freebox -DADDON_SRC_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$PREFIX/kodi/addons -DPACKAGE_ZIP=1 $PREFIX/kodi/cmake/addons
make package-addons
```

Ajout du `cd build`, qui manque peut-être d'ailleurs [pour Leïa](https://github.com/aassif/pvr.freebox/wiki/%28FR%29-Compilation).
