### ISSUE TITLE
Installation Windows

### ISSUE THREAD

**Issue by Wolfy76700** [aassif/pvr.freebox#8]
Bonjour,

Je n'arrive pas à installer l'extension sur Windows, pouvez-vous m'aider SVP ?

Merci d'avance

**Comment by ninjaw** [comment]
LibreElec (RPi 2/3 + x86_64) + Android (ARMv7 + AArch64) + Linux

**Comment by aassif** [comment]
Le plugin devrait être disponible dès la prochaine version de Kodi (Matrix).

**Comment by ninjaw** [comment]
classe !

**Comment by aassif** [comment]
Avec l'arrivée imminente de Kodi 19, je clos la question.
La beta 1 de Kodi 19 est disponible sur le site officiel.
