### ISSUE TITLE
Add of Nexus branch and related version

### ISSUE THREAD

**Issue by AlwinEsch** [aassif/pvr.freebox#83]
Since Kodi 20 Nexus has been available for a some months now, it is time to create an associated Nexus branch and release for all addons, for this then maybe "20.0.0-Nexus" for here (relates to you, on Kodi side, addon major equal to Kodi major).

I'm doing this at all addons where I have access, but you would have to make a change to this one.

**Comment by AlwinEsch** [comment]
Please review https://github.com/aassif/pvr.freebox/pull/84 and to create a Nexus branch

There comes the next 1-3 days the new API change inside Kodi Matrix.
Related to:
- https://github.com/xbmc/xbmc/pull/20009
- https://github.com/xbmc/xbmc/pull/19395

**Comment by aassif** [comment]
Sorry, was really busy these days.

I will create the new branch right now.
Should I also mark it as the new default?

Regarding the version number, I'll do as it pleases you.

**Comment by AlwinEsch** [comment]
Yes, then put the master to Nexus, as long as we still go this way the best.

Hope to finally tackle this with the branches soon, as I never liked the path introduced and makes everything cumbersome :unamused:.
For me, the master should also remain the master and only create an associated branch when Kodi gets a release :smirk:.

You was a bit fast with new Nexus :sweat_smile:, thought to make this https://github.com/aassif/pvr.freebox/pull/84 first in, so that not so big difference between Matrix und Nexus by same commits come. Only confirm the request as I'm not sure that correct and good for you by the depends update and the compile error's when Kodi is set to C++17.

To become Nexus branch equal after the request on Matrix is in, is also easy as long no differences between both branches.
With this call can be a branch synchronized with other:
```
git checkout Matrix && git pull && git checkout Nexus && git merge --ff-only Matrix && git push
```
