### ISSUE TITLE
Compilation failed on Debian 11

### ISSUE THREAD

**Issue by SuperToma** [aassif/pvr.freebox#87]
Désolé si ce souci a déjà été reporté mais je ne trouve pas de solution.

J'essaye de compiler le add-on sur Debian 11 (bullseye) :
`git clone -b 19.0-Matrix https://github.com/xbmc/xbmc.git kodi`
`git clone -b Matrix https://github.com/aassif/pvr.freebox.git`

Suivi des commandes standard de compilation.
Le `cmake` se passe bien
puis le `make package-addons` me retourne l'erreur : 

`...

-- Build files have been written to: /home/toma/pvr.freebox
[ 90%] Performing forcebuild step for 'pvr.freebox'
Force build of pvr.freebox
[ 93%] Performing build step for 'pvr.freebox'
make[4]: *** No targets specified and no makefile found.  Stop.
make[3]: *** [CMakeFiles/pvr.freebox.dir/build.make:132: pvr.freebox-prefix/src/pvr.freebox-stamp/pvr.freebox-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:289: CMakeFiles/pvr.freebox.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:323: CMakeFiles/package-addons.dir/rule] Error 2
make: *** [Makefile:228: package-addons] Error 2`

Sinon, s'il y a déjà un build Matrix de disponible je suis preneur :)

Merci d'avance.

**Comment by aassif** [comment]
Bonjour,

Pour un _build_ tout prêt, je n'ai malheureusement rien à proposer.
Il me semble que seuls les _repos_ Ubuntu sont à jour.

Concernant la compilation elle-même,
la dernière fois qu'on m'avait signalé une erreur de ce genre,
il s'agissait simplement d'un problème de [répertoire courant](https://github.com/aassif/pvr.freebox/issues/79#issuecomment-864085649).

Pouvez-vous me confirmer qu'il manque bien une instruction dans le wiki ?

**Comment by SuperToma** [comment]
Bonjour,
Je confirme: les commandes spécifiées par @sleveque dans l'issue #79 fonctionnent bien.
Il faut bien supprimer tous les fichiers créés par la commande précédente erronée avec `git clean -f -d` sinon cela ,ne fonctionne toujours pas.
L'instruction est donc bien manquante dans le wiki.
Merci beaucoup ! 
Je regarde demain si le add-on compilé est fonctionnel :)
