### ISSUE TITLE
eurosport

### ISSUE THREAD

**Issue by cyr06** [aassif/pvr.freebox#89]
Merci pour ce plugin, il est vraiment facile d'utilisation, même pour qu'un qui connait pas grand chose à tout ça.
Y a t il un moyen d'accéder à Eurosport 1 et 2 via ce plugin ? J'ai ces chaines dans mon abonnement mais je ne trouve aucun plugin pour les afficher sur mon kodi.
Merci et bon we!

**Comment by ninjaw** [comment]
drole de question injustifiée, c'est un plugin multiposte, eurosport n'est pas en multiposte, mais ca tu le savais déjà.
