### ISSUE TITLE
freebox mini 4k

### ISSUE THREAD

**Issue by CircleCode** [aassif/pvr.freebox#9]
J'ai installé cet addon sur un raspberry pi 3 faisant tourner raspbian.
l'EPG ets correctement récupéré. En revanche, lorsque j'essaie d'ouvrir une chaîne, j'ai les logs suivants :
```
2019-05-19 12:07:50.028 T:1902363488  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/Toutes les chaînes/pvr.freebox_201.pvr
2019-05-19 12:07:50.032 T:1538069216  NOTICE: Creating InputStream
2019-05-19 12:07:50.035 T:1538069216  NOTICE: Creating Demuxer
2019-05-19 12:08:00.110 T:1538069216 WARNING: could not find codec parameters for rtsp://mafreebox.freebox.fr/fbxtv_pub/stream?namespace=1&service=201&flavour=ld
2019-05-19 12:08:00.111 T:1538069216   ERROR: OpenDemuxStream - Error creating demuxer
2019-05-19 12:08:00.112 T:1538069216  NOTICE: CVideoPlayer::OnExit()
2019-05-19 12:08:05.949 T:1902363488  NOTICE: CVideoPlayer::CloseFile()
2019-05-19 12:08:05.949 T:1902363488  NOTICE: VideoPlayer: waiting for threads to exit
2019-05-19 12:08:05.950 T:1902363488  NOTICE: VideoPlayer: finished waiting
```
Je ne sais pas si c'est censé fonctionner avec la mini 4k, mais je suis prêt à faire des investigations pour tenter de résoudre le problème.

Puis-je fournir d'autres logs ?

**Comment by ninjaw** [comment]
bien sur que ca marche, la mini4k server est une revolution.
installe libreelec ? comme ca t'aura tout le necessaire

**Comment by aassif** [comment]
Mode bridge ?

**Comment by CircleCode** [comment]
@aassif désolé pour  la réponse tardive.
Mode bridge.
Mais lorsque je branche le freebox player, il fonctionne correctement.

**Comment by aassif** [comment]
Selon moi, le plus simple est d'activer le serveur VPN de la Freebox (PPTP ou OpenVPN routé).
Le RPi 3, une fois configuré également, pourra alors accéder à toutes les chaînes.

**Comment by aassif** [comment]
Encore mieux : accéder directement au Freebox Server via wifi en plus du câblage local !
Cependant, je crois que les chaînes TNT ne seront plus accessibles.

**Comment by ninjaw** [comment]
en mode normal la wifi inclue la tnt

**Comment by CircleCode** [comment]
> Selon moi, le plus simple est d'activer le serveur VPN de la Freebox (PPTP ou OpenVPN routé).

Impossible en mode bridge :-(

> Encore mieux : accéder directement au Freebox Server via wifi en plus du câblage local !

Le wifi est désactivé sur ma freebox... (et n'est de toute façon pas disponible en mode bridge !

Quelques éléments supplémentaires :
- la freebox est en mode bridge
- j'y ai connecté un routeur sous openwrt
- du routeur part un cable ethernet
  - lorsque je connecte le freebox player à ce cable, il est capable de diffuser la télé
  - lorsque je connecte le raspberry à la place du freebox player, j'obtiens l'erreur déjà mentionnée

D'autres idées ?

je peux lancer des commandes réseau sur le pi si besoin pour diagnostiquer le problème...

**Comment by CircleCode** [comment]
Note :
le freebox server est bien accessible, puisque j'ai bien eu la demande d'autorisation pour l'enregistrement…

**Comment by CircleCode** [comment]
Problème identifié (cf #14 pour une piste de résolution) :
La raison en est que RTSP est un protocole un peu spécial (il n'est pas vraiment client/serveur) : certes, le PC se connecte à la Freebox mais le flux vidéo lui-même n'est pas envoyé dans cette connexion, mais séparement sous forme de paquets UDP. Le routeur utilisé ici (openwrt) n'a apparemment pas de mécanisme de suivi des sessions RTSP (conntracker) qui permettrait de transmettre automatiquement ces paquets UDP à la bonne machine. Il faut donc mettre en place une redirection de port, qui nécessite #14 pour fonctionner.
