### ISSUE TITLE
bug qualité

### ISSUE THREAD

**Issue by MagicOneFr** [aassif/pvr.freebox#91]
Salut
J'ai juste un petit problème à remonter : Quand on configure l'addon en qualité "haute" on a une video SD. Alors que si on met la qualité en "auto", on a du 1080p (à la sauce free).
Je me serais attendu que la qualité 'haute" match au moins avec la qualité "auto".
Ce n'est pas très grave, mais si un jour vous avez le temps de jeter un oeil...
C'est très visible sur france 2 par exemple, la video en qualité "haute" est bien moins bonne sur un match de rugby par exemple.
Merci et bravo pour cet addon qui marche très bien à part ça.

**Comment by aassif** [comment]
J'ai vérifié dans le code et n'ai pas trouvé d'erreur.
En toute logique, le comportement doit être similaire sur la télévision.
Si tel est le cas, je ne peux pas faire grand chose...
