### ISSUE TITLE
[Portage Gentoo vers Debian] Add-on couldn't be loaded

### ISSUE THREAD

**Issue by jaypeche** [aassif/pvr.freebox#95]
Je suis un utilisateur Gentoo et kodi-pvr-freebox fonctionne parfaitement avec Kodi 19.4 et PVR Freebox 19.0.0.

Gentoo offre la possibilité de créer des packages compilés, j'ai donc une archive [kodi-pvr-freebox-19.0.0.tbz2](https://ftp.pingwho.org/pub/gentoo/ftp/distfiles/kodi-pvr-freebox-19.0.0.tbz2) qui correspond à l'arboresence du plugin installé dans le système après sa compilation.

Mon idée dans un premier temps, est d'installer la meme version Kodi 19.4 sur ma VM Debian que sur ma machine hôte Gentoo.
Parti de la j'ai décompresser l'archive du plugin dans le système de Debian 11 Bullseye après installation de KODI.

C'est peut etre un peu "barbare" comme méthode,  mais le plugin est bien visible dans les addons.

Par contre je n'arrive pas à l'activer, Kodi me retourne "PVR Freebox TV l'extension n'a pu être chargée". Je précise que d'un point de vue réseau, la communication est fonctionnelle. VLC récupère bien le flux TV dans la VM Debian.

J'ai pourtant essayer de satisfaire les dépendances Debian en m'inspirant des pré-requis à la compilation Gentoo  Cf [kodi-pvr-freebox-19.0.0.ebuild](https://ftp.pingwho.org/pub/gentoo/ftp/overlay/dbox2-overlay/media-plugins/kodi-pvr-freebox/kodi-pvr-freebox-19.0.0.ebuild); mais rien n'y fait.

Je souhaiterais dans l'idéal, me servir de l'archive packagée Gentoo pour créer un paquetage Debian fonctionnel. Je souhaite maitriser la création de paquets Debian, et ce serait pour moi, une bonne école.

Je me suis rendu compte que dans les sources du plugin, il y avait déja un répertoire Debian dont je pourrais m'inspiré.

Pensez-vous qu'il y a encore des dépendances à satisfaire; auquel cas, serait il possible de me les détailler ?
Ou est-ce que le problème vous a déjà été remonté ?

Avez vous également déja essayer de packager pour Debian ou Raspbian ?
J'envisage de suivre la [doc debian](https://www.debian.org/doc/manuals/maint-guide/first.fr.html) suivante pour le packaging car Gentoo y est mentionné.

Fichier log (mode debug) : [https://gist.github.com/20fd2bab839e5bc107dfe3fa407adacb](https://gist.github.com/20fd2bab839e5bc107dfe3fa407adacb)

Une piste avec des librairies manquantes : [ldd pvr.freebox.so
](https://gist.github.com/e68285f1ed3cc9a3ec5fe5c328e39429)

En vous remerciant.

**Comment by aassif** [comment]
Bonjour,

Je crains manquer d'expérience pour pouvoir vous répondre car je code uniquement sous Ubuntu.
Tous les autres _builds_ sont compilés par le Jenkins de Kodi.

La ligne 726 de votre fichier _log_ me semble néanmoins étrange.
Êtes-vous sûr de votre arborescence ?

Bon courage !
