### ISSUE TITLE
Compatibilté avec Nexus pour windows x64 et android arm64-v8a

### ISSUE THREAD

**Issue by boyle94** [aassif/pvr.freebox#97]
Bonjour,
Je tenais d'abord à vous remercier pour tous le travail fourni par passion et la collaboration des personnes à ce projet.
J'utilisais cet add-on avec kodi matrix 19.4 version windows x64 et android arm64-v8a. Tout marchait bien.
Après recherche et à moins qu'une information m'ait échappée, l’add-on pvr.freebox n'a pas été porté pour la version Nexus sous ces mêmes environnements.
Pensez-vous que vous le ferez prochainement ?
Merci pour vos projets.
Bien à vous.

**Comment by aassif** [comment]
Bonjour,
Tout d'abord, merci pour les compliments !
Normalement, le travail de portage a été effectué il y a bien longtemps déjà.
Je vais essayer de regarder ça rapidement.
À bientôt !

**Comment by aassif** [comment]
@AlwinEsch
I only realize now that the addon isn't available anymore.
It seems that Jenkins doesn't build it because of some ownership issue.
Would you happen to know how I can solve this issue?

**Comment by aassif** [comment]
https://jenkins.kodi.tv/view/Addons/job/aassif/job/pvr.freebox/job/Nexus/75/console

**Comment by aassif** [comment]
@fuzzard According to this [post](https://forum.kodi.tv/showthread.php?tid=198833&pid=3112499#pid3112499), I understand I need your help.

**Comment by fuzzard** [comment]
Have you installed the github app linked in that post?

**Comment by aassif** [comment]
Yes, I did :)

**Comment by fuzzard** [comment]
Jenkins changes have been made.

Edit, i should point out, android is failing to build (both arm and aarch64)

**Comment by aassif** [comment]
Thanks a lot!
I'm on it :)

**Comment by StefanoPierini** [comment]
Hi, 
I was using KODI under android in the free box player (freebox mini 4K), thank you a lot for writing this add-on!

I have the same problem, Kodi was automatically updated and I lost the freebox channels.

**Comment by aassif** [comment]
@fuzzard @AlwinEsch Android builds seem to fail because of OpenSSL. Do you have an idea?

**Comment by aassif** [comment]
Thanks to @fuzzard, test builds are available [here](https://jenkins.kodi.tv/blue/organizations/jenkins/aassif%2Fpvr.freebox/detail/PR-98/1/artifacts).
@boyle94 @StefanoPierini Can you test it?

**Comment by IndonesYann** [comment]
Test on MiBox3 ARM version, working like a charm, thanks a lot @aassif & @fuzzard !
ça marche à nouveau sur Kodi v20.1 sur Mibox3, Merci beaucoup @aassif & @fuzzard !

**Comment by aassif** [comment]
Merci pour le test !

**Comment by StefanoPierini** [comment]
It also works for me! Thank you very much!
Stefano.

**Comment by boyle94** [comment]
Test's results :
windows x86-64 : works fine.
arm64-v8a on nvidia shield 2019 : works fine.
I've noticed problems to read freebox revolution's records (on both systems).
Add-on sends "file read failure".
Thanks a lot for reactivity.

**Comment by MagicOneFr** [comment]
testé sur win64 : fonctionne très bien.
Beau boulot.

**Comment by StefanoPierini** [comment]
It works for me (freebox mini 4K player)! Thank you very much!
Stefano.

**Comment by sousouille** [comment]
Bonjour, comment installer le zip sur Nvidia shield ? Je l'ai rappatrié sur la box et le zip n'est pas vu par Kodi comme installable.

**Comment by boyle94** [comment]
@sousouille , on peut le faire même depuis un lecteur réseau avec Nexus et versions antérieures récentes.
- Bien autoriser sources inconnues dans menu Kodi "paramètres/système/extensions".
- Sous Android de Nvdia, l'appli kodi doit avoir toujours l'autorisation d'accéder aux fichiers et contenus multimédia.

Ensuite, le zip est visible et installable depuis le menu kodi "extension/installer d'un fichier zip".
Cela a marché pour moi sans aucune autre manip.

**Comment by aassif** [comment]
Désolé pour le dérangement.
La compilation échouait également sur Apple Silicon.
Maintenant que c'est réparé, les _builds_ devraient à nouveau être déployées sur les miroirs.

**Comment by aassif** [comment]
https://mirrors.kodi.tv/addons/nexus/

**Comment by boyle94** [comment]
Pas de soucis @aassif c'est un travail d'équipe et merci encore pour vos actions rapides.
Juste une dernière remarque ou voulez-vous que j'ouvre un autre point ? Est-ce que le problème de la non lecture des enregistrements freebox revolution est normale par rapport à ce que j'indiquais il y a 2 jours ou je ne suis peut-être pas au courant d'une information ?

**Comment by aassif** [comment]
@boyle94 Effectivement, mieux vaudrait ouvrir un autre ticket.
Car, non, ce n'est pas normal du tout :)

Les mêmes enregistrements pouvaient bien être lus sous Matrix ?

**Comment by aassif** [comment]
Et si vous êtes en mode _bridge_, il faut remplacer le nom NetBIOS par `mafreebox.freebox.fr` dans les réglages.
